import type { Site } from "./types";
import { project } from "./usmap";

// ---------------------------------------------------------------------------
// The board. Real coordinates, real cases — the map doubles as a tour of
// American UFO folklore, which is most of the reason to set this in the USA.
//
// yield  = harvest value (extractive races)
// appeal = tour value (Nordic); 0 means there is nothing to look at
// risk   = suspicion multiplier for working here
// ---------------------------------------------------------------------------

export const SITES: Site[] = [
  // --- Home bases ---------------------------------------------------------
  {
    id: "roswell",
    name: "Roswell Field",
    place: "Roswell, N.M.",
    state: "NM",
    lat: 33.39,
    lon: -104.52,
    kind: "base",
    yield: 0,
    appeal: 0,
    risk: 1,
    note: "Your predecessor put a craft into a sheep pasture here and the weather-balloon story only just held. You inherit his suspicion.",
  },
  {
    id: "shasta",
    name: "Mount Shasta Terminal",
    place: "Siskiyou County, Calif.",
    state: "CA",
    lat: 41.41,
    lon: -122.19,
    kind: "base",
    yield: 0,
    appeal: 0,
    risk: 0.8,
    note: "The Lemurians supposedly kept a city under this mountain. The charter desk is on the north face, above the treeline.",
  },
  {
    id: "dulce",
    name: "Dulce Substation",
    place: "Dulce, N.M.",
    state: "NM",
    lat: 36.94,
    lon: -107.0,
    kind: "base",
    yield: 0,
    appeal: 0,
    risk: 0.9,
    note: "Seven levels down under the Archuleta Mesa. The upper floors are a formality; the work happens where the elevator has no buttons.",
  },

  // --- Ranches: cattle, biomass, nobody counts them carefully -------------
  {
    id: "snippy",
    name: "Snippy Ranch",
    place: "Alamosa, Colo.",
    state: "CO",
    lat: 37.47,
    lon: -105.87,
    kind: "ranch",
    yield: 11,
    appeal: 0,
    risk: 1.3,
    note: "A horse found stripped to bone from the neck up, 1967. The first mutilation case anyone bothered to photograph.",
  },
  {
    id: "cimarron",
    name: "Cimarron Range",
    place: "Cimarron, N.M.",
    state: "NM",
    lat: 36.51,
    lon: -104.92,
    kind: "ranch",
    yield: 9,
    appeal: 0,
    risk: 0.9,
    note: "High grass, thin population, and a sheriff who covers four hundred square miles alone.",
  },
  {
    id: "amarillo",
    name: "Panhandle Feedlots",
    place: "Amarillo, Tex.",
    state: "TX",
    lat: 35.22,
    lon: -101.83,
    kind: "ranch",
    yield: 14,
    appeal: 0,
    risk: 1.2,
    note: "Two hundred thousand head in open pens. The single richest biomass draw in the sector, and the most watched.",
  },
  {
    id: "valentine",
    name: "Sandhills Spread",
    place: "Valentine, Neb.",
    state: "NE",
    lat: 42.87,
    lon: -100.55,
    kind: "ranch",
    yield: 10,
    appeal: 0,
    risk: 0.7,
    note: "Grass dunes to the horizon. You can work all night here and the nearest window is eleven miles off.",
  },
  {
    id: "milescity",
    name: "Tongue River Ranch",
    place: "Miles City, Mont.",
    state: "MT",
    lat: 46.41,
    lon: -105.84,
    kind: "ranch",
    yield: 10,
    appeal: 0,
    risk: 0.8,
    note: "Montana lost so many cattle to mutilation in the seventies the FBI opened a file and then quietly closed it.",
  },
  {
    id: "elko",
    name: "Ruby Valley Stock",
    place: "Elko, Nev.",
    state: "NV",
    lat: 40.83,
    lon: -115.76,
    kind: "ranch",
    yield: 9,
    appeal: 0,
    risk: 1.1,
    note: "Close enough to Groom Lake that anything in the sky gets blamed on the Air Force. Useful cover, dangerous neighbours.",
  },
  {
    id: "vale",
    name: "Malheur Basin",
    place: "Vale, Ore.",
    state: "OR",
    lat: 43.98,
    lon: -117.24,
    kind: "ranch",
    yield: 8,
    appeal: 0,
    risk: 0.6,
    note: "Empty, cold, and reliably overcast. The single quietest place to work in the western sector.",
  },
  {
    id: "guthrie",
    name: "Four Sixes Pasture",
    place: "Guthrie, Tex.",
    state: "TX",
    lat: 33.62,
    lon: -100.32,
    kind: "ranch",
    yield: 12,
    appeal: 0,
    risk: 1,
    note: "A ranch the size of a small county. The hands are armed, incurious, and paid not to talk.",
  },
  {
    id: "bellefourche",
    name: "Belle Fourche Range",
    place: "Belle Fourche, S.D.",
    state: "SD",
    lat: 44.67,
    lon: -103.85,
    kind: "ranch",
    yield: 9,
    appeal: 0,
    risk: 0.8,
    note: "The geographic centre of the nation, which the tourist board mentions and the ranchers do not.",
  },
  {
    id: "dodgecity",
    name: "Dodge City Yards",
    place: "Dodge City, Kan.",
    state: "KS",
    lat: 37.75,
    lon: -100.02,
    kind: "ranch",
    yield: 12,
    appeal: 0,
    risk: 1.1,
    note: "Rail yards and slaughterhouses. Cattle vanish here on their own schedule, which is excellent cover.",
  },
  {
    id: "pecos",
    name: "Pecos River Ranch",
    place: "Pecos, Tex.",
    state: "TX",
    lat: 31.42,
    lon: -103.49,
    kind: "ranch",
    yield: 10,
    appeal: 0,
    risk: 0.9,
    note: "Scrub, oil derricks, and a river nobody swims in. Good approach from the south at low altitude.",
  },
  {
    id: "lusk",
    name: "Niobrara Grazing",
    place: "Lusk, Wyo.",
    state: "WY",
    lat: 42.76,
    lon: -104.45,
    kind: "ranch",
    yield: 8,
    appeal: 0,
    risk: 0.6,
    note: "The least populated county in the least populated state. Practically a private airfield.",
  },

  // --- Towns: people, witnesses, specimens --------------------------------
  {
    id: "kelly",
    name: "Kelly Farmstead",
    place: "Hopkinsville, Ky.",
    state: "KY",
    lat: 36.86,
    lon: -87.49,
    kind: "town",
    yield: 11,
    appeal: 0,
    risk: 1.4,
    note: "In 1955 the Sutton family emptied two shotguns into small silver figures on the roof all night. The goblins, allegedly, did not mind.",
  },
  {
    id: "pointpleasant",
    name: "Point Pleasant",
    place: "Mason County, W.Va.",
    state: "WV",
    lat: 38.84,
    lon: -82.14,
    kind: "town",
    yield: 10,
    appeal: 0,
    risk: 1.5,
    note: "Something with red eyes and a wingspan haunted the old TNT plant for thirteen months, and then the bridge came down.",
  },
  {
    id: "exeter",
    name: "Exeter",
    place: "Rockingham County, N.H.",
    state: "NH",
    lat: 42.98,
    lon: -70.95,
    kind: "town",
    yield: 9,
    appeal: 0,
    risk: 1.3,
    note: "1965: a teenager and two patrolmen watched a thing the size of a barn drift over the Dining place. It made the wire services.",
  },
  {
    id: "pascagoula",
    name: "Pascagoula Landing",
    place: "Pascagoula, Miss.",
    state: "MS",
    lat: 30.37,
    lon: -88.56,
    kind: "town",
    yield: 12,
    appeal: 0,
    risk: 1.2,
    note: "Two shipyard workers taken off a fishing pier in 1973. Left alone in a room afterward, they kept telling each other the same story.",
  },
  {
    id: "flatwoods",
    name: "Flatwoods Hollow",
    place: "Braxton County, W.Va.",
    state: "WV",
    lat: 38.72,
    lon: -80.65,
    kind: "town",
    yield: 9,
    appeal: 0,
    risk: 1.1,
    note: "Schoolboys and a National Guardsman met a ten-foot thing in a hood on a hilltop in 1952 and ran the whole way home.",
  },
  {
    id: "aurora",
    name: "Aurora",
    place: "Wise County, Tex.",
    state: "TX",
    lat: 33.06,
    lon: -97.51,
    kind: "town",
    yield: 8,
    appeal: 0,
    risk: 0.9,
    note: "An airship hit Judge Proctor's windmill in 1897 and the pilot, they say, is buried under a Texas historical marker.",
  },
  {
    id: "levelland",
    name: "Levelland",
    place: "Hockley County, Tex.",
    state: "TX",
    lat: 33.59,
    lon: -102.38,
    kind: "town",
    yield: 10,
    appeal: 0,
    risk: 1.2,
    note: "1957: fifteen separate drivers reported their engines dying under a glowing object. The Air Force blamed ball lightning. Fifteen times.",
  },
  {
    id: "socorro",
    name: "Socorro Arroyo",
    place: "Socorro, N.M.",
    state: "NM",
    lat: 34.06,
    lon: -106.89,
    kind: "town",
    yield: 10,
    appeal: 0,
    risk: 1.3,
    note: "Patrolman Lonnie Zamora found landing gear scorch marks and an insignia he sketched but was told not to publish.",
  },
  {
    id: "lincoln",
    name: "Franconia Notch",
    place: "Lincoln, N.H.",
    state: "NH",
    lat: 44.05,
    lon: -71.67,
    kind: "town",
    yield: 13,
    appeal: 0,
    risk: 1.6,
    note: "Betty and Barney Hill lost two hours on Route 3 in 1961 and got them back under hypnosis. The star map is the problem.",
  },
  {
    id: "mcminnville",
    name: "Trent Farm",
    place: "McMinnville, Ore.",
    state: "OR",
    lat: 45.21,
    lon: -123.2,
    kind: "town",
    yield: 8,
    appeal: 0,
    risk: 1.1,
    note: "Mrs. Trent took two photographs from the yard in 1950. Nobody has yet proved they are fakes, which is its own problem.",
  },
  {
    id: "elmwood",
    name: "Elmwood",
    place: "Pierce County, Wis.",
    state: "WI",
    lat: 44.78,
    lon: -92.15,
    kind: "town",
    yield: 9,
    appeal: 0,
    risk: 1,
    note: "The town declared itself the UFO capital of the world and started building a landing pad to prove it.",
  },
  {
    id: "fyffe",
    name: "Fyffe",
    place: "DeKalb County, Ala.",
    state: "AL",
    lat: 34.45,
    lon: -85.9,
    kind: "town",
    yield: 9,
    appeal: 0,
    risk: 1.1,
    note: "The police chief and his assistant both saw it. The town now holds an annual festival, which complicates the denial strategy.",
  },
  {
    id: "gulfbreeze",
    name: "Gulf Breeze",
    place: "Santa Rosa County, Fla.",
    state: "FL",
    lat: 30.44,
    lon: -87.21,
    kind: "town",
    yield: 11,
    appeal: 0,
    risk: 1.4,
    note: "A contractor produced a suspiciously excellent run of photographs. Half the field thinks it's a hoax, which is useful to you either way.",
  },

  // --- Landmarks: what the Nordics are actually selling --------------------
  {
    id: "grandcanyon",
    name: "Grand Canyon",
    place: "Coconino County, Ariz.",
    state: "AZ",
    lat: 36.06,
    lon: -112.14,
    kind: "landmark",
    yield: 0,
    appeal: 18,
    risk: 1.2,
    note: "A mile deep and two billion years of strata. The single best-selling view on the charter list.",
  },
  {
    id: "devilstower",
    name: "Devils Tower",
    place: "Crook County, Wyo.",
    state: "WY",
    lat: 44.59,
    lon: -104.72,
    kind: "landmark",
    yield: 0,
    appeal: 16,
    risk: 0.9,
    note: "A laccolith the Lakota call Bear Lodge. Tourists arrive already expecting something to land on it.",
  },
  {
    id: "sedona",
    name: "Sedona Vortices",
    place: "Yavapai County, Ariz.",
    state: "AZ",
    lat: 34.87,
    lon: -111.76,
    kind: "landmark",
    yield: 0,
    appeal: 14,
    risk: 1,
    note: "Red rock and four alleged energy vortices. The locals will explain your own craft to you at length.",
  },
  {
    id: "niagara",
    name: "Niagara Falls",
    place: "Niagara County, N.Y.",
    state: "NY",
    lat: 43.1,
    lon: -78.92,
    kind: "landmark",
    yield: 0,
    appeal: 15,
    risk: 1.5,
    note: "Six million cubic feet a minute. Spectacular, and swarming with honeymooners holding cameras.",
  },
  {
    id: "yellowstone",
    name: "Yellowstone Caldera",
    place: "Park County, Wyo.",
    state: "WY",
    lat: 44.43,
    lon: -110.59,
    kind: "landmark",
    yield: 0,
    appeal: 17,
    risk: 0.8,
    note: "A supervolcano with a gift shop. Premium fare — the geothermal display reads as engineered to most visitors.",
  },
  {
    id: "craterlake",
    name: "Crater Lake",
    place: "Klamath County, Ore.",
    state: "OR",
    lat: 42.94,
    lon: -122.11,
    kind: "landmark",
    yield: 0,
    appeal: 14,
    risk: 0.6,
    note: "The deepest water in the country, sitting in a collapsed mountain. Approach from the north is unobserved nine nights in ten.",
  },
  {
    id: "badlands",
    name: "The Badlands",
    place: "Pennington County, S.D.",
    state: "SD",
    lat: 43.85,
    lon: -102.34,
    kind: "landmark",
    yield: 0,
    appeal: 12,
    risk: 0.7,
    note: "Banded rock and no cover for forty miles. Cheap to reach, and the light at dawn does most of the work.",
  },
  {
    id: "monumentvalley",
    name: "Monument Valley",
    place: "San Juan County, Utah",
    state: "UT",
    lat: 37.06,
    lon: -110.15,
    kind: "landmark",
    yield: 0,
    appeal: 15,
    risk: 0.8,
    note: "Sandstone buttes on Navajo land. Every tourist who has seen a Western thinks they have already been here.",
  },
  {
    id: "mammoth",
    name: "Mammoth Cave",
    place: "Edmonson County, Ky.",
    state: "KY",
    lat: 37.19,
    lon: -86.1,
    kind: "landmark",
    yield: 0,
    appeal: 13,
    risk: 0.9,
    note: "Four hundred miles of surveyed passage and nobody has found the end. Subsurface approach — almost no exposure.",
  },
  {
    id: "sanddunes",
    name: "Great Sand Dunes",
    place: "Saguache County, Colo.",
    state: "CO",
    lat: 37.73,
    lon: -105.51,
    kind: "landmark",
    yield: 0,
    appeal: 12,
    risk: 0.7,
    note: "Seven hundred feet of sand against the Sangre de Cristos. It looks like somewhere else entirely, which is the selling point.",
  },
  {
    id: "salem",
    name: "Salem",
    place: "Essex County, Mass.",
    state: "MA",
    lat: 42.52,
    lon: -70.9,
    kind: "landmark",
    yield: 0,
    appeal: 11,
    risk: 1.4,
    note: "The tourists want to see where the hangings happened. A tasteless charter, and it sells out first every season.",
  },
  {
    id: "coralcastle",
    name: "Coral Castle",
    place: "Homestead, Fla.",
    state: "FL",
    lat: 25.5,
    lon: -80.44,
    kind: "landmark",
    yield: 0,
    appeal: 13,
    risk: 1.1,
    note: "One man moved eleven hundred tons of limestone alone and never said how. Popular stop; some guests recognise the technique.",
  },

  // --- Anomalies: thin places ---------------------------------------------
  {
    id: "marfa",
    name: "Marfa Lights",
    place: "Presidio County, Tex.",
    state: "TX",
    lat: 30.31,
    lon: -104.02,
    kind: "anomaly",
    yield: 7,
    appeal: 14,
    risk: 0.5,
    note: "Lights on the Mitchell Flat since 1883. Anything you fly here gets filed under the existing phenomenon, free of charge.",
  },
  {
    id: "brownmtn",
    name: "Brown Mountain",
    place: "Burke County, N.C.",
    state: "NC",
    lat: 35.93,
    lon: -81.82,
    kind: "anomaly",
    yield: 7,
    appeal: 12,
    risk: 0.6,
    note: "The Cherokee had a story about these lights before the Geological Survey turned up to explain them as trains.",
  },
  {
    id: "bermuda",
    name: "The Triangle Gate",
    place: "off Key West, Fla.",
    state: "FL",
    lat: 24.56,
    lon: -81.78,
    kind: "anomaly",
    yield: 9,
    appeal: 16,
    risk: 1.3,
    note: "A natural aperture, free to use and violently unreliable. Flight 19 went in and did not come out where it should have.",
    startLocked: true,
    offshore: true,
  },
  {
    id: "cahokia",
    name: "Cahokia Mounds",
    place: "Madison County, Ill.",
    state: "IL",
    lat: 38.66,
    lon: -90.06,
    kind: "anomaly",
    yield: 8,
    appeal: 13,
    risk: 0.9,
    note: "A city of twenty thousand, abandoned before Columbus. Monks Mound is aligned to something nobody has satisfactorily named.",
  },
  {
    id: "serpentmound",
    name: "Serpent Mound",
    place: "Adams County, Ohio",
    state: "OH",
    lat: 39.03,
    lon: -83.43,
    kind: "anomaly",
    yield: 7,
    appeal: 12,
    risk: 0.8,
    note: "Quarter-mile earthwork on the rim of a genuine impact crater. Whoever built it knew the crater was there.",
  },
  {
    id: "skinwalker",
    name: "Skinwalker Ranch",
    place: "Uintah County, Utah",
    state: "UT",
    lat: 40.26,
    lon: -109.89,
    kind: "anomaly",
    yield: 12,
    appeal: 10,
    risk: 1.8,
    note: "Five hundred acres where the cattle, the lights and the dogs all behave wrongly. Rich, and it does not like being worked.",
    startLocked: true,
  },
  {
    id: "superstition",
    name: "Superstition Range",
    place: "Pinal County, Ariz.",
    state: "AZ",
    lat: 33.43,
    lon: -111.42,
    kind: "anomaly",
    yield: 8,
    appeal: 11,
    risk: 1,
    note: "People walk in after the Lost Dutchman's gold and a reliable fraction never walk out. The attrition is already priced in locally.",
  },

  // --- Military: rich, loud, armed ----------------------------------------
  {
    id: "area51",
    name: "Groom Lake",
    place: "Lincoln County, Nev.",
    state: "NV",
    lat: 37.24,
    lon: -115.81,
    kind: "military",
    yield: 18,
    appeal: 0,
    risk: 2.2,
    note: "They are reverse-engineering your predecessor's wreck in Hangar 18 and doing badly. Everything you take from here is already yours.",
    startLocked: true,
  },
  {
    id: "wrightpat",
    name: "Wright-Patterson AFB",
    place: "Dayton, Ohio",
    state: "OH",
    lat: 39.83,
    lon: -84.05,
    kind: "military",
    yield: 16,
    appeal: 0,
    risk: 2,
    note: "Project Blue Book files, and the bodies. The single most valuable thing on the continent to recover, and the best defended.",
    startLocked: true,
  },
  {
    id: "whitesands",
    name: "White Sands Range",
    place: "Doña Ana County, N.M.",
    state: "NM",
    lat: 32.78,
    lon: -106.32,
    kind: "military",
    yield: 13,
    appeal: 9,
    risk: 1.7,
    note: "Gypsum flats, captured V-2s, and tracking cameras pointed permanently at the sky. They photograph you for free.",
  },
  {
    id: "losalamos",
    name: "Los Alamos Lab",
    place: "Los Alamos, N.M.",
    state: "NM",
    lat: 35.88,
    lon: -106.31,
    kind: "military",
    yield: 15,
    appeal: 0,
    risk: 1.9,
    note: "The Hill. Green fireballs over the technical area in 1948 put the whole staff on edge and none of them were yours.",
    startLocked: true,
  },
  {
    id: "oakridge",
    name: "Oak Ridge",
    place: "Anderson County, Tenn.",
    state: "TN",
    lat: 36.01,
    lon: -84.27,
    kind: "military",
    yield: 14,
    appeal: 0,
    risk: 1.8,
    note: "Enriched uranium and a restricted airspace that has logged more intrusions than it admits.",
    startLocked: true,
  },
  {
    id: "hanford",
    name: "Hanford Site",
    place: "Benton County, Wash.",
    state: "WA",
    lat: 46.55,
    lon: -119.49,
    kind: "military",
    yield: 13,
    appeal: 0,
    risk: 1.6,
    note: "Plutonium production reactors on the Columbia. Vast, poisoned, and almost entirely unobserved at ground level.",
  },
  {
    id: "canaveral",
    name: "Cape Canaveral",
    place: "Brevard County, Fla.",
    state: "FL",
    lat: 28.49,
    lon: -80.58,
    kind: "military",
    yield: 14,
    appeal: 11,
    risk: 1.9,
    note: "They are about to start throwing their own things into orbit, which will make this sector considerably harder to work.",
  },
  {
    id: "malmstrom",
    name: "Malmstrom AFB",
    place: "Great Falls, Mont.",
    state: "MT",
    lat: 47.51,
    lon: -111.19,
    kind: "military",
    yield: 15,
    appeal: 0,
    risk: 1.8,
    note: "Ten Minuteman silos went offline at once while something sat over the launch control facility. The report is still classified.",
    startLocked: true,
  },
  {
    id: "cheyennemtn",
    name: "Cheyenne Mountain",
    place: "El Paso County, Colo.",
    state: "CO",
    lat: 38.74,
    lon: -104.85,
    kind: "military",
    yield: 17,
    appeal: 0,
    risk: 2.1,
    note: "Two thousand feet of granite over the room where they decide whether the thing on the radar is a threat.",
    startLocked: true,
  },
  {
    id: "edwards",
    name: "Edwards AFB",
    place: "Kern County, Calif.",
    state: "CA",
    lat: 34.91,
    lon: -117.88,
    kind: "military",
    yield: 13,
    appeal: 0,
    risk: 1.7,
    note: "Muroc Dry Lake. Test pilots here see things weekly and have a professional interest in not reporting them.",
  },

  // --- Cities: press, population, contacts --------------------------------
  {
    id: "dc",
    name: "Washington",
    place: "District of Columbia",
    state: "MD",
    lat: 38.98,
    lon: -76.9,
    kind: "city",
    yield: 9,
    appeal: 8,
    risk: 2.4,
    note: "In July 1952 formations crossed the Capitol two weekends running and the Air Force held the biggest press conference since the war.",
  },
  {
    id: "nyc",
    name: "New York",
    place: "New York, N.Y.",
    state: "NY",
    lat: 40.79,
    lon: -73.95,
    kind: "city",
    yield: 12,
    appeal: 9,
    risk: 2.3,
    note: "Eight million people and every wire service on the continent. Nothing happens here quietly.",
  },
  {
    id: "chicago",
    name: "Chicago",
    place: "Cook County, Ill.",
    state: "IL",
    lat: 41.88,
    lon: -87.63,
    kind: "city",
    yield: 11,
    appeal: 7,
    risk: 2,
    note: "Rail hub, stockyards, and a lakefront that gives every witness an unobstructed view for nine miles.",
  },
  {
    id: "la",
    name: "Los Angeles",
    place: "Los Angeles, Calif.",
    state: "CA",
    lat: 34.05,
    lon: -118.24,
    kind: "city",
    yield: 11,
    appeal: 8,
    risk: 2.1,
    note: "They shelled their own sky for an hour in 1942 and hit nothing. The city has been primed ever since.",
  },
  {
    id: "denver",
    name: "Denver",
    place: "Denver, Colo.",
    state: "CO",
    lat: 39.74,
    lon: -104.99,
    kind: "city",
    yield: 9,
    appeal: 7,
    risk: 1.7,
    note: "Mile-high, ringed by mountains that hide an approach, and the regional MJ-12 desk keeps an office downtown.",
  },
  {
    id: "seattle",
    name: "Seattle",
    place: "King County, Wash.",
    state: "WA",
    lat: 47.61,
    lon: -122.33,
    kind: "city",
    yield: 9,
    appeal: 8,
    risk: 1.8,
    note: "Overcast two hundred days a year, which is worth more to you than the population is worth to anyone.",
  },
  {
    id: "miami",
    name: "Miami",
    place: "Dade County, Fla.",
    state: "FL",
    lat: 25.82,
    lon: -80.31,
    kind: "city",
    yield: 10,
    appeal: 9,
    risk: 1.9,
    note: "The staging port for the Triangle. Half the charter traffic in the sector clears through here.",
  },
];

export const SITE_BY_ID: Record<string, Site> = Object.fromEntries(
  SITES.map((s) => [s.id, s]),
);

/** Screen position in viewBox units — precomputed once, never changes. */
export const SITE_XY: Record<string, [number, number]> = Object.fromEntries(
  SITES.map((s) => [s.id, project(s.lon, s.lat)]),
);

export function siteXY(id: string): [number, number] {
  return SITE_XY[id] ?? [0, 0];
}
