import type { EventDef } from "../types";

// The other races. Whichever one you picked, the other two are out there as
// patrons, rivals and complications — plus the Draco above you, the Federation
// holding your licence, and everyone's opinion of how you are running things.

export const FACTIONS_EVENTS: EventDef[] = [
  {
    id: "fed-audit",
    tier: 3,
    tags: ["faction"],
    weight: 8,
    headline: "FEDERATION COMPLIANCE AUDIT",
    dek: "A scheduled review of your operating licence. They want exposure figures, cargo manifests, and an explanation for the discrepancy in both.",
    choices: [
      {
        label: "Submit honest books",
        effect: { standing: 8, cash: -50 },
        note: "Full disclosure of your disclosure. They fine you modestly and note the candour.",
      },
      {
        label: "Dress the figures",
        cost: { cash: 60 },
        effect: { standing: 4 },
        backfire: {
          chance: 0.3,
          effect: { standing: -18, cash: -120 },
          note: "They audit the audit. Falsifying a return is a considerably worse offence than the return.",
        },
        note: "A creative accounting of the exposure ledger. It passes without comment.",
      },
      {
        label: "Stall them",
        effect: { standing: -8, disclosure: -2 },
        note: "Procedural delay. It buys a quarter and costs you a quarter's worth of goodwill.",
      },
    ],
  },
  {
    id: "fed-licence-warning",
    tier: 4,
    tags: ["faction", "crisis"],
    weight: 4,
    minDisclosure: 55,
    headline: "FORMAL WARNING ON THE HARVESTING LICENCE",
    dek: "The masquerade clause is the core term of your licence and you are in visible breach of it. The next letter will not be a warning.",
    choices: [
      {
        label: "Buy a compliance extension",
        cost: { cash: 280, standing: 10 },
        effect: { disclosure: -10 },
        note: "An expensive stay of execution. The clock resets; the terms do not improve.",
      },
      {
        label: "Accept a supervised operating period",
        effect: { standing: 12, disclosure: -14, cash: -140, suspicionAll: -20 },
        note: "A Federation observer rides along and everything slows to a crawl. It works.",
      },
      {
        label: "Ignore the letter",
        effect: { standing: -20, disclosure: 6 },
        note: "You do not reply. Somewhere, a file is moved to a different desk.",
      },
    ],
  },
  {
    id: "draco-quota",
    tier: 2,
    tags: ["faction"],
    weight: 8,
    headline: "DRACO QUOTA REVISION",
    dek: "The aristocracy has reviewed your output and found it wanting. They would like more, sooner, and they are not interested in your exposure problem.",
    choices: [
      {
        label: "Meet the quota",
        cost: { cash: 90 },
        effect: { faction: { draco: 10 }, disclosure: 5, suspicionAll: 6, goal: 40 },
        note: "You run hot for a month and make the number. They stop writing letters.",
      },
      {
        label: "Negotiate it down",
        cost: { standing: 5 },
        effect: { faction: { draco: -6 }, standing: -3 },
        note: "The Federation backs your position on safety grounds. The Draco remember being overruled.",
      },
      {
        label: "Refuse",
        effect: { faction: { draco: -14 }, standing: 4 },
        note: "A flat no. It is the correct decision and it makes a permanent enemy of your landlord.",
      },
    ],
  },
  {
    id: "draco-offer",
    tier: 3,
    tags: ["faction"],
    weight: 6,
    minDisclosure: 40,
    headline: "THE DRACO PROPOSE DROPPING THE MASQUERADE",
    dek: "Their position is that secrecy is now costing more than it returns, and that an open occupation would be simpler for everyone. They are not entirely wrong.",
    choices: [
      {
        label: "Decline and reaffirm the masquerade",
        effect: { faction: { draco: -10, federation: 8, nordic: 8 }, standing: 6 },
        note: "You hold the line. Everyone except the Draco is relieved.",
      },
      {
        label: "Take their money and stay quiet about it",
        effect: { cash: 260, faction: { draco: 8, federation: -6 }, disclosure: 6 },
        note: "A substantial retainer for a decision you have not actually made. The Federation smells it.",
      },
      {
        label: "Hear them out properly",
        effect: { faction: { draco: 12, federation: -10, nordic: -12 }, disclosure: 10, cash: 180 },
        note: "You do not commit, but you listen, and word gets around that you listened.",
      },
    ],
  },
  {
    id: "nordic-sanction",
    tier: 3,
    tags: ["faction"],
    weight: 6,
    races: ["grey", "mantid"],
    minDisclosure: 35,
    headline: "NORDIC DELEGATION LODGES A PROTEST",
    dek: "They have been watching your operating methods and they have opinions about them, which they have now put in writing to the Federation.",
    choices: [
      {
        label: "Adopt their handling standards",
        cost: { cash: 145 },
        effect: { faction: { nordic: 12 }, standing: 6, suspicionAll: -10 },
        note: "Slower, gentler, more expensive procedures. Your exposure profile improves markedly.",
      },
      {
        label: "Ignore the protest",
        effect: { faction: { nordic: -12 }, standing: -6 },
        note: "You carry on. The complaint sits on file and will be cited against you later.",
      },
      {
        label: "Counter-brief the Federation",
        cost: { cash: 80 },
        effect: { faction: { nordic: -8 }, standing: 3 },
        backfire: {
          chance: 0.28,
          effect: { standing: -10, faction: { nordic: -6 } },
          note: "Your counter-brief was checked. Two of its claims were not true.",
        },
        note: "A vigorous submission on operational necessity. It lands well enough.",
      },
    ],
  },
  {
    id: "nordic-tourists-stray",
    tier: 2,
    tags: ["faction", "weird"],
    weight: 6,
    races: ["nordic"],
    headline: "A TOUR GROUP HAS WANDERED OFF",
    dek: "Six Pleiadian guests stepped away from the observation platform at {place} for a closer look. Four have come back.",
    choices: [
      {
        label: "Sweep the area immediately",
        cost: { cash: 95 },
        effect: { disclosure: -3, suspicion: 6, faction: { nordic: 4 } },
        note: "Both recovered within the hour, delighted with themselves, having spoken to no one.",
      },
      {
        label: "Wait — they will come back",
        effect: { disclosure: 7, suspicion: 4, faction: { nordic: -8 } },
        backfire: {
          chance: 0.4,
          effect: { disclosure: 8, spoilSite: true },
          note: "One of them had a very long conversation with a park ranger before returning.",
        },
        note: "They return at dawn, sunburnt and thrilled. Nobody appears to have seen them.",
      },
    ],
  },
  {
    id: "mantid-gate",
    tier: 2,
    tags: ["faction"],
    weight: 7,
    races: ["grey", "nordic"],
    headline: "THE DIRECTORATE WITHHOLDS CERTIFICATION",
    dek: "The Mantids will not sign off on your premium output without one of their own aboard, and they are not offering one cheaply.",
    choices: [
      {
        label: "Pay for a Mantid observer",
        cost: { cash: 165 },
        effect: { faction: { mantid: 10 }, cash: 60 },
        note: "Expensive, unsettling company, and your output grades two bands higher for it.",
      },
      {
        label: "Sell uncertified and take the discount",
        effect: { faction: { mantid: -8 }, cash: 45 },
        note: "It moves at a poor price. The Directorate notes that you went around them.",
      },
      {
        label: "Forge the certification",
        cost: { cash: 50 },
        effect: { cash: 120 },
        backfire: {
          chance: 0.4,
          effect: { faction: { mantid: -20, federation: -8 }, standing: -12 },
          note: "Mantid certification is not a thing that can be forged, as you have now discovered publicly.",
        },
        note: "It clears. You will not try that again.",
      },
    ],
  },
  {
    id: "mantid-breakthrough",
    tier: 2,
    tags: ["faction", "boon"],
    weight: 5,
    races: ["mantid"],
    headline: "THE LINE HOLDS THROUGH A FULL GENERATION",
    dek: "A viable sequence, stable, reproducing true. The Directorate is as close to pleased as it is capable of being.",
    choices: [
      {
        label: "Publish internally and take the credit",
        effect: { faction: { mantid: 12 }, standing: 5, goal: 1 },
        note: "Your name goes on it. Directorate patronage improves immediately and materially.",
      },
      {
        label: "Trade the technique to the Greys",
        effect: { cash: 220, faction: { mantid: -10, grey: 10 } },
        note: "They pay well for it. The Directorate considers this a serious breach of professional conduct.",
      },
    ],
  },
  {
    id: "rival-operator",
    tier: 3,
    tags: ["faction", "crisis"],
    weight: 6,
    minDisclosure: 25,
    headline: "A RIVAL IS WORKING YOUR SECTOR",
    dek: "Someone else is running craft over {place} without a licence, sloppily, and every incident they cause lands on your ledger.",
    choices: [
      {
        label: "Report them to the Federation",
        cost: { standing: 3 },
        effect: { standing: 6, suspicionAll: -12, faction: { grey: -6 } },
        note: "Enforcement arrives within the month. The rival's craft are impounded and the pressure comes off you.",
      },
      {
        label: "Cut a deal with them",
        cost: { cash: 110 },
        effect: { cash: 150, disclosure: 4, standing: -5 },
        note: "You take a cut of an unlicensed operation, which is precisely as dangerous as it sounds.",
      },
      {
        label: "Drive them out yourself",
        cost: { cash: 140 },
        effect: { suspicionAll: -8, disclosure: 3 },
        backfire: {
          chance: 0.3,
          effect: { loseCraft: true, disclosure: 6 },
          note: "They fought back, competently, and you are down a hull.",
        },
        note: "A short, ugly, entirely deniable dispute. They relocate to Argentina.",
      },
    ],
  },
  {
    id: "grey-undercut",
    tier: 2,
    tags: ["faction"],
    weight: 6,
    races: ["nordic", "mantid"],
    headline: "ZETA SUBCONTRACTORS UNDERCUT YOUR PRICE",
    dek: "They will do it faster and for two-thirds of your rate. They will also do it badly, but the buyers are not paying for care.",
    choices: [
      {
        label: "Match the price",
        effect: { cash: -80, faction: { grey: -5 } },
        note: "You hold the contract at a margin that barely justifies the fuel.",
      },
      {
        label: "Compete on quality",
        cost: { cash: 70 },
        effect: { faction: { mantid: 6, nordic: 6 }, cash: 130 },
        note: "You let them have the cheap work and take the buyers who can tell the difference.",
      },
      {
        label: "Let them have it and watch",
        effect: { suspicionAll: 8, faction: { grey: 4 }, disclosure: 3 },
        note: "They take the contract and stir up a great deal of trouble doing it. Some of it lands on you.",
      },
    ],
  },
  {
    id: "fed-standing-bonus",
    tier: 1,
    tags: ["faction", "boon"],
    weight: 5,
    headline: "COMMENDATION FROM THE COMPLIANCE OFFICE",
    dek: "A clean quarter. They have noticed, which they almost never do, and they have written it down.",
    choices: [
      {
        label: "Bank the goodwill",
        effect: { standing: 10 },
        note: "Filed. It will be worth something the next time you need a favour, and you will.",
      },
      {
        label: "Convert it to an operating grant",
        effect: { cash: 170, standing: 2 },
        note: "You cash the commendation in for working capital. Pragmatic, and slightly resented.",
      },
    ],
  },
  {
    id: "fed-inspector-visit",
    tier: 2,
    tags: ["faction"],
    weight: 6,
    headline: "AN INSPECTOR ARRIVES UNANNOUNCED",
    dek: "No notice, no appointment, and a clipboard. They intend to watch a full night's operations from the inside.",
    choices: [
      {
        label: "Run a flawless shift",
        cost: { cash: 75 },
        effect: { standing: 9, suspicionAll: -8 },
        note: "Everything by the book, everything slow, nothing out of place. They leave satisfied.",
      },
      {
        label: "Show them the good routes only",
        effect: { standing: 3 },
        backfire: {
          chance: 0.3,
          effect: { standing: -12 },
          note: "They asked to see a route you had not prepared, which was rather the point of arriving unannounced.",
        },
        note: "A curated tour. They see three well-run corridors and none of the others.",
      },
      {
        label: "Suspend operations for the visit",
        effect: { standing: 5, cash: -60 },
        note: "Nothing flies. There is nothing to inspect, which is itself a kind of answer.",
      },
    ],
  },
  {
    id: "draco-gift",
    tier: 2,
    tags: ["faction", "boon"],
    weight: 5,
    headline: "REPTILIAN HEAVY WORKS SENDS A DEMONSTRATOR",
    dek: "A hull on loan, no charge, no obligation stated. The obligation is nonetheless understood.",
    choices: [
      {
        label: "Accept the craft",
        effect: { grantCraft: "triangle", faction: { draco: 8, nordic: -5 } },
        note: "It is a good hull and it was free, and now you owe them a favour of unspecified size.",
      },
      {
        label: "Decline it",
        effect: { faction: { draco: -6 }, standing: 4 },
        note: "Returned unopened. The Federation approves; the Draco file it away.",
      },
    ],
  },
  {
    id: "fed-fine",
    tier: 2,
    tags: ["faction"],
    weight: 6,
    minDisclosure: 30,
    headline: "EXPOSURE PENALTY ASSESSED",
    dek: "A schedule of fines calculated against your reported disclosure figure. The arithmetic is not in dispute.",
    choices: [
      {
        label: "Pay it",
        cost: { cash: 130 },
        effect: { standing: 5 },
        note: "Settled in full and on time. It is expensive and it keeps the licence clean.",
      },
      {
        label: "Appeal",
        cost: { cash: 40 },
        effect: { standing: -3 },
        backfire: {
          chance: 0.35,
          effect: { cash: -180, standing: -8 },
          note: "The appeal failed and the costs were awarded against you.",
        },
        note: "The penalty is reduced on a technicality about measurement windows.",
      },
      {
        label: "Refuse to pay",
        effect: { standing: -14, cash: 0 },
        note: "The debt accrues. So does the Federation's interest in your other arrangements.",
      },
    ],
  },
  {
    id: "nordic-charter-offer",
    tier: 2,
    tags: ["faction", "boon"],
    weight: 5,
    races: ["grey", "mantid"],
    headline: "THE NORDICS OFFER A JOINT CHARTER",
    dek: "They want access to a site you control and they are willing to pay for it properly, in advance, with conditions.",
    choices: [
      {
        label: "Take the charter",
        effect: { cash: 190, faction: { nordic: 10 }, suspicion: -8 },
        note: "Their guests are quiet, their money is good, and their handling standards cool the site down.",
      },
      {
        label: "Refuse — it is your site",
        effect: { faction: { nordic: -7 } },
        note: "You keep the exclusivity. They will remember being turned away.",
      },
    ],
  },
  {
    id: "mantid-demand-shift",
    tier: 2,
    tags: ["faction"],
    weight: 6,
    races: ["mantid"],
    headline: "THE DIRECTORATE REVISES ITS TRAIT SCHEDULE",
    dek: "What was in demand last quarter is now surplus. The new schedule is on your desk and it invalidates most of your holdings.",
    choices: [
      {
        label: "Retool to the new schedule",
        cost: { cash: 90 },
        effect: { faction: { mantid: 8 }, spawnSpecimens: 3 },
        note: "Expensive, immediate, and it puts fresh viable stock in the pipeline.",
      },
      {
        label: "Dump the old holdings cheaply",
        effect: { cash: 110, faction: { mantid: -5 } },
        note: "Sold at a loss to a Grey subcontractor who does not ask what the traits are for.",
      },
    ],
  },
  {
    id: "fed-rival-claim",
    tier: 3,
    tags: ["faction", "crisis"],
    weight: 5,
    minDisclosure: 45,
    headline: "A RIVAL BIDS FOR YOUR LICENCE",
    dek: "They argue your exposure record demonstrates unfitness and that the Earth licence should be re-auctioned. It is not a frivolous filing.",
    choices: [
      {
        label: "Fight it on your record",
        cost: { standing: 12 },
        effect: { standing: -4, faction: { federation: 5 } },
        note: "Your compliance history is good enough to carry the hearing. Only just.",
      },
      {
        label: "Buy the claimant off",
        cost: { cash: 300 },
        effect: { disclosure: -4 },
        note: "The filing is withdrawn on undisclosed terms. Everyone understands what happened.",
      },
      {
        label: "Let it go to auction and bid",
        cost: { cash: 220 },
        effect: { standing: 6, disclosure: -6 },
        backfire: {
          chance: 0.3,
          effect: { cash: -200, standing: -14 },
          note: "You were outbid and then billed for the process. A comprehensively bad quarter.",
        },
        note: "You keep the licence at a price and the challenge is settled for good.",
      },
    ],
  },
  {
    id: "draco-enforcer",
    tier: 3,
    tags: ["faction", "crisis"],
    weight: 5,
    headline: "A DRACO ENFORCER IS ON SITE",
    dek: "Sent to observe, allegedly. He has been aboard three of your craft without asking and has opinions about your crew composition.",
    choices: [
      {
        label: "Accommodate him",
        cost: { cash: 100 },
        effect: { faction: { draco: 9 }, suspicionAll: 5 },
        note: "He gets what he wants and leaves a favourable report. Your crews run more suspicious under his methods.",
      },
      {
        label: "Have the Federation remove him",
        cost: { standing: 8 },
        effect: { faction: { draco: -12, federation: 6 } },
        note: "Jurisdiction is asserted and he is escorted off. The Draco take this personally.",
      },
      {
        label: "Ignore him and carry on",
        effect: { faction: { draco: -6 }, disclosure: 3 },
        note: "He observes, writes, and leaves. The report is not favourable.",
      },
    ],
  },
  {
    id: "faction-summit",
    tier: 3,
    tags: ["faction"],
    weight: 5,
    minDisclosure: 30,
    headline: "ALL PARTIES ARE CALLED TO A SUMMIT",
    dek: "Draco, Nordic, Directorate and the compliance office, in one room, about you. Attendance is not technically compulsory.",
    choices: [
      {
        label: "Attend and take the criticism",
        effect: { standing: 8, faction: { nordic: 5, mantid: 5, draco: -3 }, disclosure: -4 },
        note: "You sit through four hours of it. Everyone leaves marginally better disposed toward you.",
      },
      {
        label: "Send a deputy",
        effect: { standing: -4, faction: { draco: 3 } },
        note: "A calculated slight. The Draco enjoy it; nobody else does.",
      },
      {
        label: "Do not attend",
        effect: { standing: -10, faction: { nordic: -6, mantid: -6, federation: -6 } },
        note: "They proceed without you and reach conclusions in your absence, as people do.",
      },
    ],
  },
  {
    id: "fed-tech-release",
    tier: 2,
    tags: ["faction", "boon"],
    weight: 5,
    headline: "A TECHNOLOGY RELEASE IS APPROVED",
    dek: "Your standing has cleared the threshold for the next equipment tier. There is paperwork, and then there is a hangar.",
    choices: [
      {
        label: "Take the hull",
        cost: { standing: 8 },
        effect: { grantCraft: "cigar" },
        note: "Signed over and delivered. A serious increase in capacity for a serious amount of goodwill.",
      },
      {
        label: "Take the cash equivalent",
        cost: { standing: 5 },
        effect: { cash: 240 },
        note: "Liquidated instead. Less impressive, considerably more flexible.",
      },
    ],
  },
  {
    id: "nordic-uplift",
    tier: 3,
    tags: ["faction"],
    weight: 4,
    races: ["nordic"],
    minDisclosure: 35,
    headline: "THE UPLIFT QUESTION IS RAISED AGAIN",
    dek: "A faction within your own charter argues that the humans should be told, gently, on a schedule, by you. It is not a fringe view any more.",
    choices: [
      {
        label: "Support a slow, controlled contact programme",
        effect: { faction: { nordic: 12, federation: -8, draco: -6 }, disclosure: 8, standing: -6 },
        note: "A century-long plan, begun. The Federation regards this as the beginning of a breach.",
      },
      {
        label: "Hold the line on non-interference",
        effect: { faction: { nordic: -6, federation: 8 }, standing: 6, disclosure: -4 },
        note: "The charter's founding principle is reaffirmed. The reformers are disappointed and quiet.",
      },
    ],
  },
  {
    id: "grey-strike",
    tier: 2,
    tags: ["faction", "crisis"],
    weight: 5,
    races: ["grey"],
    headline: "THE DRONE POOL STOPS WORK",
    dek: "Nobody has ever seen Short Greys refuse an instruction before. They are simply standing in the hangar, all of them, facing the same direction.",
    choices: [
      {
        label: "Improve their conditions",
        cost: { cash: 120 },
        effect: { faction: { grey: 10, nordic: 6 }, suspicionAll: -8 },
        note: "Whatever it was, it is addressed. Error rates fall noticeably afterward.",
      },
      {
        label: "Bring in Tall Grey overseers",
        cost: { cash: 85 },
        effect: { faction: { grey: -6 }, suspicionAll: -5 },
        note: "Discipline is restored quickly and the hangar is a colder place to work.",
      },
      {
        label: "Wait them out",
        effect: { cash: -70, faction: { grey: -10 }, disclosure: 2 },
        note: "Four nights of no operations. They resume without explanation and something has changed.",
      },
    ],
  },
  {
    id: "fed-observer-embed",
    tier: 2,
    tags: ["faction"],
    weight: 5,
    minDisclosure: 25,
    headline: "A COMPLIANCE OBSERVER IS ASSIGNED TO YOU",
    dek: "Permanently, or until your figures improve. She has a desk in your operations room now and she takes notes continuously.",
    choices: [
      {
        label: "Cooperate fully",
        effect: { standing: 10, suspicionAll: -10, cash: -70 },
        note: "Everything slows and everything cleans up. Your exposure profile has never looked better.",
      },
      {
        label: "Work around her",
        effect: { standing: -8, disclosure: 3 },
        backfire: {
          chance: 0.3,
          effect: { standing: -16, cash: -110 },
          note: "She documented the workaround in detail for six weeks before saying anything.",
        },
        note: "A second set of operations she is not shown. It holds, for now.",
      },
    ],
  },
];
