import type { EventDef } from "../types";

// The human layer. Collaborators, assets, antagonists — everyone on the ground
// who knows something, wants something, or is about to find out.

export const HUMANS: EventDef[] = [
  {
    id: "mj12-retainer",
    tier: 2,
    tags: ["human"],
    weight: 8,
    headline: "MAJESTIC 12 PRESENTS THE QUARTERLY INVOICE",
    dek: "The arrangement is not cheap and the arrangement is not optional. A man in a hotel room slides a figure across the table and waits.",
    choices: [
      {
        label: "Pay in full",
        cost: { cash: 120 },
        effect: { faction: { mj12: 8 }, disclosure: -3, suspicionAll: -5 },
        note: "Paid without argument. Doors stay closed, files stay lost, and reporters keep hitting walls.",
      },
      {
        label: "Pay half and promise the rest",
        cost: { cash: 60 },
        effect: { faction: { mj12: -3 }, disclosure: 1 },
        note: "He accepts it. He also writes something down, which he did not do last time.",
      },
      {
        label: "Refuse",
        effect: { faction: { mj12: -14 }, disclosure: 5, suspicionAll: 4 },
        note: "The retainer lapses. Within a month, three separate agencies rediscover their curiosity.",
      },
    ],
  },
  {
    id: "mj12-techtransfer",
    tier: 2,
    tags: ["human"],
    weight: 7,
    headline: "THE HUMANS WANT ANOTHER PIECE OF THE DRIVE",
    dek: "Their reverse-engineering programme has stalled again. They are asking for a component, and they are asking in the tone of people who feel owed.",
    choices: [
      {
        label: "Hand over something genuine",
        cost: { cash: 90 },
        effect: { faction: { mj12: 12, federation: -6 }, disclosure: -4 },
        note: "A working assembly. They will not understand it for forty years, and the goodwill is immediate.",
      },
      {
        label: "Hand over something plausible and useless",
        effect: { faction: { mj12: 3 } },
        backfire: {
          chance: 0.35,
          effect: { faction: { mj12: -16 }, disclosure: 6 },
          note: "They have better metallurgists than you credited. They know exactly what you gave them.",
        },
        note: "An impressive-looking dead end. It buys two years of enthusiastic, wasted effort.",
      },
      {
        label: "Refuse outright",
        effect: { faction: { mj12: -10 }, standing: 4, disclosure: 2 },
        note: "The Federation approves of the restraint. Your human partners emphatically do not.",
      },
    ],
  },
  {
    id: "mj12-raid-warning",
    tier: 3,
    tags: ["human", "crisis"],
    weight: 5,
    minDisclosure: 35,
    headline: "YOUR MAN INSIDE SENDS A WARNING",
    dek: "A raid is being planned on a site in {place}. He is telling you because he is still being paid. That may not last.",
    choices: [
      {
        label: "Evacuate the site immediately",
        cost: { cash: 80 },
        effect: { suspicion: -20, disclosure: -3 },
        note: "They arrive to an empty building with the dust undisturbed. It costs you a week of throughput.",
      },
      {
        label: "Leave a convincing decoy",
        cost: { cash: 145 },
        effect: { suspicion: -14, disclosure: -6, faction: { mj12: 5 } },
        note: "They find exactly enough to write a satisfying report and close the inquiry.",
      },
      {
        label: "Do nothing and dare them",
        effect: { disclosure: 8, suspicion: 15, faction: { movement: 6 } },
        backfire: {
          chance: 0.4,
          effect: { loseRoute: true, disclosure: 6 },
          note: "They took a craft intact. That is the single worst outcome available.",
        },
        note: "They come in hard. What they find is ambiguous, and ambiguity is survivable.",
      },
    ],
  },
  {
    id: "human-abductee-book",
    tier: 3,
    tags: ["human"],
    weight: 6,
    minDisclosure: 25,
    headline: "ABDUCTEE'S ACCOUNT REACHES PRINT",
    dek: "A first-person book, a sympathetic publisher, and a hypnotist's transcript in an appendix. It is selling.",
    choices: [
      {
        label: "Buy out the print run",
        cost: { cash: 165 },
        effect: { disclosure: -6 },
        backfire: {
          chance: 0.25,
          effect: { disclosure: 8, faction: { movement: 10 } },
          note: "A bookshop owner noticed one buyer taking every copy and phoned a reporter.",
        },
        note: "Quietly, through eleven different accounts, in eleven different cities.",
      },
      {
        label: "Wipe the author",
        cost: { cash: 130 },
        effect: { disclosure: -7, faction: { nordic: -8 } },
        note: "The second edition is withdrawn because the author no longer recalls writing the first.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 6, faction: { movement: 8 } },
        note: "It goes into paperback. Every subsequent account will borrow its structure.",
      },
    ],
  },
  {
    id: "human-movement-rally",
    tier: 2,
    tags: ["human"],
    weight: 7,
    minDisclosure: 20,
    headline: "DISCLOSURE MEETING DRAWS A CROWD IN {place}",
    dek: "{believer} has filled a union hall. There are two hundred people inside and a reporter from {paper}.",
    choices: [
      {
        label: "Infiltrate and steer it",
        cost: { cash: 70 },
        effect: { faction: { movement: -8 }, disclosure: -3 },
        note: "Your man takes the floor with a theory about lizard people. The reporter leaves early.",
      },
      {
        label: "Let them talk",
        effect: { faction: { movement: 3 }, disclosure: 2 },
        note: "It costs nothing and it grows a little. Sometimes that is the correct trade.",
      },
      {
        label: "Have the hall's licence pulled",
        cost: { cash: 45 },
        effect: { faction: { movement: 6 }, disclosure: 1, suspicion: -3 },
        note: "The meeting is cancelled, which convinces every attendee they were right.",
      },
    ],
  },
  {
    id: "human-cult",
    tier: 2,
    tags: ["human", "weird"],
    weight: 6,
    headline: "CONTACTEE CULT ESTABLISHES ITSELF NEAR {place}",
    dek: "Forty people in white have bought a ranch and are waiting for you specifically. Their leader claims a standing appointment.",
    choices: [
      {
        label: "Let them believe — they are excellent cover",
        effect: { disclosure: -4, faction: { movement: -5 }, suspicion: 4 },
        note: "Every serious witness in the county is now tarred by association with the people in white.",
      },
      {
        label: "Actually make the appointment",
        cost: { cash: 60 },
        effect: { disclosure: 4, faction: { nordic: 8, movement: -4 }, cash: 70 },
        note: "You land. They are overjoyed, entirely sincere, and they tithe. The Nordics find this charming.",
      },
      {
        label: "Disperse them",
        cost: { cash: 85 },
        effect: { disclosure: -2, faction: { movement: 5, nordic: -6 } },
        note: "A tax question, a zoning dispute, and the ranch is repossessed by spring.",
      },
    ],
  },
  {
    id: "human-mib",
    tier: 2,
    tags: ["human"],
    weight: 7,
    headline: "MEN IN DARK SUITS CALL ON A WITNESS",
    dek: "Two of them, in a black sedan, asking questions they already knew the answers to. They were not yours.",
    choices: [
      {
        label: "Find out whose they were",
        cost: { cash: 95 },
        effect: { disclosure: -2, faction: { mj12: -4 } },
        note: "MJ-12, freelancing. They are running their own suppression and not telling you.",
      },
      {
        label: "Send your own, properly",
        cost: { cash: 75 },
        effect: { disclosure: -5, suspicion: -6, faction: { movement: 4 } },
        note: "The witness recants comprehensively. The visit becomes its own local legend.",
      },
      {
        label: "Stay out of it",
        effect: { disclosure: 2, faction: { movement: 3 } },
        note: "Whoever they were, the witness stopped talking. You will take the result and not ask.",
      },
    ],
  },
  {
    id: "human-farmer-shotgun",
    tier: 1,
    tags: ["human"],
    weight: 8,
    needsRoute: true,
    kinds: ["ranch", "town"],
    headline: "FARMER FIRES ON CRAFT AT {place}",
    dek: "Both barrels, at close range, at a hull he could not possibly damage. He is telling everyone and he has the empty shells.",
    choices: [
      {
        label: "Compensate him for livestock 'losses'",
        cost: { cash: 55 },
        effect: { disclosure: -3, suspicion: -6 },
        note: "An anonymous cheque for more than the herd was worth. He stops talking and starts farming.",
      },
      {
        label: "Stop working that pasture",
        effect: { suspicion: -10, cash: -20 },
        note: "You pull the route back a few miles. He never sees anything again and is quietly disappointed.",
      },
      {
        label: "Ignore him",
        effect: { disclosure: 3, suspicion: 5 },
        note: "He becomes the county character. Every visiting journalist gets the shells shown to them.",
      },
    ],
  },
  {
    id: "human-hospital",
    tier: 3,
    tags: ["human", "crisis"],
    weight: 4,
    needsRoute: true,
    minHeat: 30,
    headline: "PATIENT ADMITTED WITH UNEXPLAINED BURNS",
    dek: "Radiation pattern consistent with nothing in the county. The attending physician has written to the state health board.",
    choices: [
      {
        label: "Treat him properly and quietly",
        cost: { cash: 110 },
        effect: { disclosure: -5, faction: { nordic: 6 } },
        note: "He recovers fully, which he would not have done otherwise, and remembers a car accident.",
      },
      {
        label: "Suppress the physician's letter",
        cost: { cash: 70 },
        effect: { disclosure: -3, faction: { nordic: -4 } },
        backfire: {
          chance: 0.28,
          effect: { disclosure: 7, faction: { movement: 8 } },
          note: "Doctors keep copies and this one keeps very good records.",
        },
        note: "It never reaches the board. The patient is discharged with a diagnosis of industrial exposure.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 6, suspicion: 6, faction: { movement: 5 } },
        note: "The state health board investigates. They are thorough and they are not looking for aircraft.",
      },
    ],
  },
  {
    id: "human-senator",
    tier: 4,
    tags: ["human", "crisis"],
    weight: 3,
    minDisclosure: 55,
    headline: "SENATE COMMITTEE ANNOUNCES HEARINGS",
    dek: "Subpoena power, a sympathetic chairman, and a witness list that includes three people you have already had to deal with once.",
    choices: [
      {
        label: "Have MJ-12 bury it in committee",
        cost: { cash: 320, standing: 8 },
        effect: { disclosure: -14, faction: { mj12: -10 } },
        note: "It dies in procedure without a single day of testimony. It costs them enormously to do.",
      },
      {
        label: "Compromise the chairman",
        cost: { cash: 200 },
        effect: { disclosure: -10, faction: { movement: 6 } },
        backfire: {
          chance: 0.3,
          effect: { disclosure: 16, faction: { movement: 14, federation: -10 } },
          note: "He went public with the attempt. The hearings now have a second subject: the cover-up.",
        },
        note: "An old matter is recalled to his attention. His enthusiasm for the topic evaporates.",
      },
      {
        label: "Let it proceed",
        effect: { disclosure: 12, faction: { federation: -10, movement: 12 } },
        note: "Televised. Three days. The Federation watches every minute of it with you.",
      },
    ],
  },
  {
    id: "human-recruit-hybrid",
    tier: 2,
    tags: ["human", "boon"],
    weight: 5,
    headline: "A HYBRID PASSES THE FIELD TEST",
    dek: "Six months embedded in a county sheriff's office. Nobody noticed. Nobody was ever going to notice.",
    choices: [
      {
        label: "Place more of them",
        cost: { cash: 140 },
        effect: { disclosure: -6, suspicionAll: -10, faction: { mantid: 6 } },
        note: "Eleven placements across three states. Ground-level exposure drops away almost entirely.",
      },
      {
        label: "Keep the programme small",
        effect: { disclosure: -2, faction: { mantid: 3 } },
        note: "One asset, well placed, is harder to lose than eleven spread thin.",
      },
    ],
  },
  {
    id: "human-police-chief",
    tier: 2,
    tags: ["human"],
    weight: 6,
    kinds: ["town", "city"],
    headline: "POLICE CHIEF AT {place} GOES PUBLIC",
    dek: "He saw it himself, on duty, with his deputy beside him. He is not a man anybody can call a crank.",
    choices: [
      {
        label: "Put him on the payroll",
        cost: { cash: 105 },
        effect: { disclosure: -5, faction: { mj12: 4 } },
        note: "A consultancy on 'aerial phenomena liaison'. He is now the most incurious man in the county.",
      },
      {
        label: "Let the town make a festival of it",
        effect: { disclosure: 3, cash: 80, faction: { movement: 4, nordic: 3 } },
        note: "An annual UFO day, a parade, and a great deal of merchandise. Absurdity is its own cover.",
      },
      {
        label: "Wipe him",
        cost: { cash: 120 },
        effect: { disclosure: -6, suspicion: -5, faction: { nordic: -6, mj12: -3 } },
        note: "He retracts within a week and cannot say why. His deputy noticed the change.",
      },
    ],
  },
  {
    id: "human-ranchers-organise",
    tier: 3,
    tags: ["human", "crisis"],
    weight: 5,
    races: ["grey"],
    minHeat: 35,
    headline: "CATTLEMEN'S ASSOCIATION DEMANDS AN INVESTIGATION",
    dek: "Nine hundred members, a state senator on side, and four years of mutilation photographs in a bound folder.",
    choices: [
      {
        label: "Compensate the losses generously",
        cost: { cash: 190 },
        effect: { disclosure: -7, suspicionAll: -12 },
        note: "A 'predator insurance fund' appears from nowhere and pays out promptly. The pressure evaporates.",
      },
      {
        label: "Blame a cult",
        cost: { cash: 85 },
        effect: { disclosure: -5, faction: { movement: -4 } },
        backfire: {
          chance: 0.3,
          effect: { disclosure: 8, suspicion: 10 },
          note: "The FBI took the satanic-cult theory seriously and started looking properly.",
        },
        note: "Evidence of ritual activity is discovered where it will be found. The story turns lurid and useless.",
      },
      {
        label: "Ignore them",
        effect: { disclosure: 8, suspicionAll: 8, faction: { movement: 7 } },
        note: "The folder reaches Washington. It is very hard to argue with four years of photographs.",
      },
    ],
  },
  {
    id: "human-photographer-stakeout",
    tier: 2,
    tags: ["human"],
    weight: 6,
    needsRoute: true,
    headline: "PHOTOGRAPHER CAMPS ON YOUR CORRIDOR",
    dek: "He has worked out the schedule. He is not clever about much, but he was clever about this, and he has a tripod.",
    choices: [
      {
        label: "Change the schedule",
        cost: { cash: 40 },
        effect: { suspicion: -8, disclosure: -2 },
        note: "You randomise the timings. He waits three more weeks and gives up cold.",
      },
      {
        label: "Give him one good shot and burn him",
        cost: { cash: 90 },
        effect: { disclosure: -5, faction: { movement: -7 } },
        note: "The shot is spectacular and, on analysis, provably a model on a wire. He is finished.",
      },
      {
        label: "Ignore him",
        effect: { disclosure: 5, suspicion: 6 },
        note: "He gets it. Of course he gets it. He was always going to get it eventually.",
      },
    ],
  },
  {
    id: "human-army-corps",
    tier: 2,
    tags: ["human"],
    weight: 5,
    kinds: ["ranch", "anomaly", "landmark"],
    headline: "ARMY SURVEYORS ARRIVE AT {place}",
    dek: "A dam feasibility study, they say. They have theodolites and they are looking at exactly the wrong valley.",
    choices: [
      {
        label: "Have the project cancelled",
        cost: { cash: 115 },
        effect: { suspicion: -10, faction: { mj12: -3 } },
        note: "The appropriation is quietly reallocated to a different watershed. They pack up in a fortnight.",
      },
      {
        label: "Relocate operations",
        effect: { suspicion: -14, cash: -45 },
        note: "You move the whole approach forty miles. Expensive, disruptive, and completely effective.",
      },
      {
        label: "Let them survey",
        effect: { disclosure: 3, suspicion: 7 },
        note: "They find the subsurface anomaly. It goes into a report that somebody will eventually read.",
      },
    ],
  },
  {
    id: "human-radio-host",
    tier: 3,
    tags: ["human"],
    weight: 5,
    minDisclosure: 30,
    headline: "LATE-NIGHT RADIO TAKES UP THE SUBJECT",
    dek: "Four hundred stations, three million insomniacs, and a host who takes every call seriously on air.",
    choices: [
      {
        label: "Buy the advertising slot and the goodwill",
        cost: { cash: 130 },
        effect: { disclosure: -5, faction: { movement: -3 } },
        note: "A sponsor with deep pockets and firm views on programming balance. The tone moderates.",
      },
      {
        label: "Flood the phone lines with obvious cranks",
        cost: { cash: 60 },
        effect: { disclosure: -6, faction: { movement: -8 } },
        backfire: {
          chance: 0.2,
          effect: { disclosure: 5 },
          note: "The host screens calls now, and screens them well. The remaining callers are all credible.",
        },
        note: "Six weeks of hollow-earth theorists. The serious audience drifts away in disgust.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 6, faction: { movement: 9 } },
        note: "It becomes the movement's town square. Every case in the country gets aired on it.",
      },
    ],
  },
  {
    id: "human-defector",
    tier: 4,
    tags: ["human", "crisis"],
    weight: 3,
    minDisclosure: 50,
    headline: "AN INSIDER IS TALKING TO A REPORTER",
    dek: "One of MJ-12's own, with documents, dates and a reason. He has already made one telephone call too many.",
    choices: [
      {
        label: "Let MJ-12 handle their own",
        cost: { cash: 90 },
        effect: { disclosure: -10, faction: { mj12: -5, movement: 4 } },
        note: "They handle it. You are not told how and you do not ask, and the reporter's source goes quiet.",
      },
      {
        label: "Discredit the documents",
        cost: { cash: 180 },
        effect: { disclosure: -7 },
        backfire: {
          chance: 0.32,
          effect: { disclosure: 12, faction: { movement: 15 } },
          note: "Three of the documents were verifiably genuine, and now everything else looks genuine too.",
        },
        note: "Enough deliberate errors are introduced that the whole cache reads as a forgery.",
      },
      {
        label: "Buy his silence",
        cost: { cash: 240 },
        effect: { disclosure: -9, faction: { mj12: 3 } },
        note: "A number large enough to end the conversation. He retires abroad and stays retired.",
      },
    ],
  },
  {
    id: "human-fbi-file",
    tier: 2,
    tags: ["human"],
    weight: 6,
    minDisclosure: 22,
    headline: "BUREAU OPENS A FILE",
    dek: "Not on the sightings — on the people reporting them. The Bureau's interest is in subversion, which is fortunate for you.",
    choices: [
      {
        label: "Feed the subversion angle",
        cost: { cash: 65 },
        effect: { disclosure: -6, faction: { movement: -9, mj12: 4 } },
        note: "The Movement spends the next three years being investigated as a political front. Nothing gets done.",
      },
      {
        label: "Stay well clear",
        effect: { disclosure: 1 },
        note: "You do not touch it. Federal attention is not something to attract deliberately.",
      },
    ],
  },
  {
    id: "human-nurse",
    tier: 3,
    tags: ["human", "weird"],
    weight: 4,
    needsRoute: true,
    headline: "A NURSE HAS BEEN KEEPING RECORDS",
    dek: "Eleven years of admissions with the same odd cluster of symptoms, all within sixty miles of {place}. She has cross-referenced them by date and the dates match your schedule.",
    choices: [
      {
        label: "Acquire the records",
        cost: { cash: 125 },
        effect: { disclosure: -6 },
        backfire: {
          chance: 0.22,
          effect: { disclosure: 7, faction: { movement: 8 } },
          note: "She had a duplicate ledger at home, because of course she did.",
        },
        note: "A hospital records purge, entirely routine, removes eleven years of paperwork.",
      },
      {
        label: "Hire her",
        cost: { cash: 155 },
        effect: { disclosure: -7, faction: { mantid: 5 } },
        note: "A research post at triple the salary. She is delighted, and her records become yours.",
      },
      {
        label: "Ignore her",
        effect: { disclosure: 7, faction: { movement: 6 } },
        note: "She presents at a medical conference. It is careful, statistical, and hard to wave away.",
      },
    ],
  },
  {
    id: "human-town-meeting",
    tier: 1,
    tags: ["human"],
    weight: 7,
    kinds: ["town"],
    headline: "TOWN MEETING CALLED AT {place}",
    dek: "The residents want answers about the lights. {official} has agreed to attend, which was probably a mistake.",
    choices: [
      {
        label: "Plant a persuasive sceptic",
        cost: { cash: 35 },
        effect: { disclosure: -3, suspicion: -5 },
        note: "A well-briefed local explains aircraft landing lights. The room mostly accepts it.",
      },
      {
        label: "Let it run",
        effect: { disclosure: 2, suspicion: 3 },
        note: "Two hours of argument, no conclusion, and a small item in {paper}.",
      },
    ],
  },
  {
    id: "human-kid-photo",
    tier: 1,
    tags: ["human"],
    weight: 7,
    needsRoute: true,
    headline: "BOY'S SNAPSHOT WINS A COMPETITION",
    dek: "A twelve-year-old with a box camera has taken the clearest image of the year, entirely by accident, and entered it in a county fair.",
    choices: [
      {
        label: "Buy it as a curiosity",
        cost: { cash: 45 },
        effect: { disclosure: -3 },
        note: "A collector offers a sum that thrills the family. The print and negative both change hands.",
      },
      {
        label: "Let a child have his prize",
        effect: { disclosure: 3, faction: { nordic: 5 } },
        note: "He wins five dollars and a ribbon. The Nordics think rather better of you for it.",
      },
    ],
  },
  {
    id: "human-mj12-coup",
    tier: 4,
    tags: ["human", "crisis"],
    weight: 3,
    minDisclosure: 45,
    headline: "A FACTION INSIDE MAJESTIC 12 WANTS OUT",
    dek: "They have concluded the arrangement favours you unreasonably. They are correct. They are preparing to say so publicly.",
    choices: [
      {
        label: "Renegotiate on their terms",
        cost: { cash: 260 },
        effect: { faction: { mj12: 14 }, disclosure: -8, standing: -4 },
        note: "A better deal for them, ratified quickly. The Federation notes the concession without comment.",
      },
      {
        label: "Back the loyal faction",
        cost: { cash: 150 },
        effect: { faction: { mj12: 5 }, disclosure: -4 },
        backfire: {
          chance: 0.35,
          effect: { faction: { mj12: -18 }, disclosure: 12 },
          note: "You backed the wrong men. The winners remember exactly who funded the other side.",
        },
        note: "An internal reorganisation. The dissenters are transferred to places without telephones.",
      },
      {
        label: "Cut them loose entirely",
        effect: { faction: { mj12: -20 }, disclosure: 10, suspicionAll: 10 },
        note: "The arrangement ends. Forty years of accumulated protection evaporates in a fortnight.",
      },
    ],
  },
  {
    id: "human-sheriff-deal",
    tier: 1,
    tags: ["human", "boon"],
    weight: 6,
    kinds: ["ranch", "town"],
    headline: "A COUNTY SHERIFF MAKES AN OFFER",
    dek: "He knows something is happening on his patch. He does not want it stopped. He wants a retainer.",
    choices: [
      {
        label: "Take the deal",
        cost: { cash: 70 },
        effect: { suspicion: -18, disclosure: -3, faction: { mj12: 3 } },
        note: "Reports get filed as livestock predation. Nothing leaves his county.",
      },
      {
        label: "Decline politely",
        effect: { suspicion: 4 },
        note: "He shrugs. He will not make the offer twice, and he will not go out of his way for you again.",
      },
    ],
  },
  {
    id: "human-nightclub",
    tier: 1,
    tags: ["human", "weird"],
    weight: 6,
    kinds: ["city"],
    headline: "A CRAFT IS SEEN FROM A CROWDED ROOFTOP BAR",
    dek: "Two hundred people in evening dress, most of them holding a drink, and about forty of them holding a camera.",
    choices: [
      {
        label: "Cut the power to the block",
        cost: { cash: 55 },
        effect: { disclosure: -4, suspicion: -6 },
        note: "A transformer fails at exactly the right moment. In the dark, nobody agrees on what they saw.",
      },
      {
        label: "Ignore it — they have all been drinking",
        effect: { disclosure: 2, suspicion: 4 },
        note: "The intoxication of the witnesses does most of your work for you, for free.",
      },
    ],
  },
  {
    id: "human-professor-grant",
    tier: 2,
    tags: ["human", "boon"],
    weight: 5,
    headline: "A UNIVERSITY WANTS FUNDING FOR A STUDY",
    dek: "They propose a rigorous, sceptical, well-designed investigation. Whoever pays for it will substantially shape what it concludes.",
    choices: [
      {
        label: "Fund it generously",
        cost: { cash: 175 },
        effect: { disclosure: -9, faction: { movement: -7 } },
        note: "Two years later it concludes there is nothing to investigate, at length, with excellent footnotes.",
      },
      {
        label: "Let someone else fund it",
        effect: { disclosure: 5, faction: { movement: 6 } },
        note: "{believer} funds it instead. It reaches a rather different conclusion.",
      },
    ],
  },
];
