import type { EventDef } from "../types";

// Public sightings, photographs, radar paint, and the press. The bread-and-
// butter pressure on the Disclosure meter: individually survivable, cumulative
// if you keep paying them no attention.

export const SIGHTINGS: EventDef[] = [
  {
    id: "sight-formation",
    tier: 1,
    tags: ["sighting"],
    weight: 10,
    needsRoute: true,
    headline: "LIGHTS IN FORMATION OVER {place}",
    dek: "{witness} reports {object} holding station above the treeline for some minutes. {official} is expected to comment.",
    choices: [
      {
        label: "Feed the weather-balloon line",
        cost: { cash: 30 },
        effect: { disclosure: -1, suspicion: -6 },
        note: "The wire picks up the balloon explanation and drops the story by Thursday.",
      },
      {
        label: "Buy the negatives",
        cost: { cash: 70 },
        effect: { disclosure: -3, suspicion: -10 },
        backfire: {
          chance: 0.18,
          effect: { disclosure: 4, suspicion: 8 },
          note: "The photographer had already mailed a set to his brother in Ohio.",
        },
        note: "A quiet transaction in a diner parking lot. The plates go into a furnace.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 2, suspicion: 4 },
        note: "It runs on page one of the county paper and then, mercifully, nowhere else.",
      },
    ],
  },
  {
    id: "sight-photograph",
    tier: 2,
    tags: ["sighting"],
    weight: 8,
    needsRoute: true,
    headline: "FARM COUPLE PRODUCE PHOTOGRAPH",
    dek: "Two exposures taken from a yard near {place}. The negatives appear undoctored, and {oddity}.",
    choices: [
      {
        label: "Discredit the photographer",
        cost: { cash: 90 },
        effect: { disclosure: -4, faction: { mj12: 3, movement: -6 } },
        backfire: {
          chance: 0.22,
          effect: { disclosure: 6, faction: { movement: 8 } },
          note: "The smear was clumsy and the Movement now has a martyr with a mailing list.",
        },
        note: "By the weekend he is a known fabulist with debts. Nobody prints him again.",
      },
        {
        label: "Flood the field with fakes",
        cost: { cash: 130 },
        effect: { disclosure: -6, suspicion: -4, faction: { movement: -4 } },
        note: "Forty excellent forgeries reach the same editors. The real one drowns in them.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 4, suspicion: 3 },
        note: "It gets syndicated. In thirty years it will still be in every book on the subject.",
      },
    ],
  },
  {
    id: "sight-radar",
    tier: 2,
    tags: ["sighting"],
    weight: 7,
    needsRoute: true,
    minHeat: 15,
    headline: "RADAR PAINTS UNIDENTIFIED TRACK OVER {place}",
    dek: "Ground control and an airborne interceptor held the same return for eleven minutes. The tapes exist and {official} has them.",
    choices: [
      {
        label: "Have MJ-12 requisition the tapes",
        cost: { cash: 110 },
        effect: { disclosure: -5, faction: { mj12: -4 } },
        note: "A colonel nobody can later name signs for the reels and they are never seen again.",
      },
      {
        label: "Jam the sector for a week",
        cost: { cash: 150 },
        effect: { disclosure: -3, suspicion: -14 },
        backfire: {
          chance: 0.25,
          effect: { disclosure: 5, suspicion: 10 },
          note: "A week of unexplained interference is itself now the story.",
        },
        note: "Every scope in three states runs snow. The track is unrecoverable.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 5, suspicion: 6 },
        note: "The intercept transcript will be read aloud in a Senate hearing room one day.",
      },
    ],
  },
  {
    id: "sight-airliner",
    tier: 3,
    tags: ["sighting", "crisis"],
    weight: 5,
    needsRoute: true,
    minDisclosure: 25,
    headline: "AIRLINE CREW REPORT NEAR MISS",
    dek: "A scheduled DC-6 out of {place} took violent evasive action. Ninety-one passengers, and {oddity}.",
    choices: [
      {
        label: "Settle with the airline privately",
        cost: { cash: 220 },
        effect: { disclosure: -6, faction: { mj12: 4 } },
        note: "The carrier accepts a generous explanation involving a weather balloon and a bonus.",
      },
      {
        label: "Ground your fleet for a fortnight",
        effect: { disclosure: -8, suspicionAll: -12, cash: -60 },
        note: "Everything stays in the hangar. The story dies of nothing to feed on, and so do your receipts.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 9, suspicion: 10, faction: { movement: 6 } },
        note: "Ninety-one depositions. The Civil Aeronautics Board opens a file that does not close.",
      },
    ],
  },
  {
    id: "sight-capital",
    tier: 4,
    tags: ["sighting", "crisis"],
    weight: 3,
    minDisclosure: 45,
    headline: "OBJECTS OVER THE CAPITOL TWO NIGHTS RUNNING",
    dek: "Formations crossed restricted airspace above the seat of government on consecutive weekends. The Air Force has called the largest press conference since the war.",
    choices: [
      {
        label: "Let MJ-12 stage the denial",
        cost: { cash: 300, standing: 6 },
        effect: { disclosure: -12, faction: { mj12: -8, federation: 3 } },
        note: "A general explains temperature inversions for ninety minutes. It holds. Barely.",
      },
      {
        label: "Go dark completely for a month",
        effect: { disclosure: -16, suspicionAll: -30, cash: -180 },
        note: "Total stand-down. No cargo, no income, no sightings. The city forgets by autumn.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 14, suspicionAll: 8, faction: { movement: 12, federation: -8 } },
        note: "It becomes the case every subsequent case is measured against. The Federation notices.",
      },
    ],
  },
  {
    id: "sight-engine-stall",
    tier: 2,
    tags: ["sighting"],
    weight: 7,
    needsRoute: true,
    headline: "MOTORISTS REPORT ENGINES DYING NEAR {place}",
    dek: "Eleven separate drivers on the same stretch of highway, all within two hours. Each says the engine restarted the moment the light left.",
    choices: [
      {
        label: "Blame ball lightning",
        cost: { cash: 45 },
        effect: { disclosure: -2, suspicion: -5 },
        backfire: {
          chance: 0.2,
          effect: { disclosure: 3 },
          note: "A meteorologist writes a very public letter about how that is not how ball lightning works.",
        },
        note: "{official} obliges with a statement. Most readers accept it; the physicists do not.",
      },
      {
        label: "Retune the drive spectrum",
        cost: { cash: 160 },
        effect: { disclosure: -3, suspicion: -8 },
        note: "An expensive refit. Ignition systems on the ground stop noticing you go past.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 3, suspicion: 7 },
        note: "The stretch gets a nickname and, by summer, a roadside sign.",
      },
    ],
  },
  {
    id: "sight-scramble",
    tier: 3,
    tags: ["sighting", "crisis"],
    weight: 5,
    needsRoute: true,
    minHeat: 40,
    headline: "INTERCEPTORS SCRAMBLED OVER {place}",
    dek: "Two fighters went up out of the nearest field. One pilot has not filed a report and the other has filed one that has already been reclassified.",
    choices: [
      {
        label: "Outrun them and say nothing",
        effect: { disclosure: 3, suspicion: 12 },
        note: "Trivially done. The gun camera footage is the problem, and it is now in a safe.",
      },
      {
        label: "Disable the gun cameras",
        cost: { cash: 130 },
        effect: { disclosure: -4, suspicion: -6 },
        backfire: {
          chance: 0.3,
          effect: { disclosure: 7, suspicion: 12, faction: { mj12: -6 } },
          note: "A crew chief watched the film get wiped and told his wife, who told her brother at the paper.",
        },
        note: "The reels come back fogged. The pilots are told it was a camera fault.",
      },
      {
        label: "Let them get close, then vanish",
        effect: { disclosure: -2, suspicion: 6, faction: { mj12: 5, movement: 4 } },
        note: "A deliberate demonstration. It terrifies the right people into keeping it quiet.",
      },
    ],
  },
  {
    id: "sight-flap",
    tier: 3,
    tags: ["sighting", "crisis"],
    weight: 6,
    minHeat: 55,
    headline: "SIGHTING FLAP GRIPS {place}",
    dek: "Four hundred reports in nine days. The switchboard has stopped logging them. {oddity}.",
    choices: [
      {
        label: "Stand down all routes in the state",
        effect: { disclosure: -6, suspicion: -35 },
        note: "You pull everything out. The reports keep coming for a week on momentum alone, then stop.",
      },
      {
        label: "Pay for a debunking tour",
        cost: { cash: 175 },
        effect: { disclosure: -5, suspicion: -15, faction: { movement: -5 } },
        note: "A tame astronomer does eleven town halls explaining Venus. It works better than it should.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 8, suspicion: 10, faction: { movement: 8 } },
        note: "Life magazine sends a photographer and a writer. They stay three weeks.",
      },
    ],
  },
  {
    id: "sight-film",
    tier: 2,
    tags: ["sighting"],
    weight: 6,
    needsRoute: true,
    headline: "SIXTEEN-MILLIMETRE FILM SURFACES",
    dek: "Ninety seconds of colour footage shot near {place}. It is steady, it is in focus, and that is the entire problem.",
    choices: [
      {
        label: "Acquire it at any price",
        cost: { cash: 200 },
        effect: { disclosure: -7 },
        note: "A collector's price, paid in cash, no receipt. The reel goes into the same furnace as the rest.",
      },
      {
        label: "Have a lab 'restore' it",
        cost: { cash: 85 },
        effect: { disclosure: -4 },
        backfire: {
          chance: 0.28,
          effect: { disclosure: 8, faction: { movement: 7 } },
          note: "The tampering is obvious to anyone with a loupe, and someone has a loupe.",
        },
        note: "It comes back grainier, shakier, and eight seconds shorter. Nobody can prove anything from it now.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 6, faction: { movement: 6 } },
        note: "It will be broadcast on television within the year and analysed for the next fifty.",
      },
    ],
  },
  {
    id: "sight-landing-trace",
    tier: 2,
    tags: ["sighting"],
    weight: 7,
    needsRoute: true,
    kinds: ["ranch", "town", "anomaly"],
    headline: "SCORCHED RING FOUND AT {place}",
    dek: "A circle of burnt ground forty feet across with four depressions at the compass points. Soil samples are already at a university.",
    choices: [
      {
        label: "Buy the field and plough it",
        cost: { cash: 95 },
        effect: { disclosure: -4, suspicion: -8 },
        note: "A land company nobody has heard of purchases the parcel and turns it over by Tuesday.",
      },
      {
        label: "Intercept the soil samples",
        cost: { cash: 60 },
        effect: { disclosure: -3 },
        backfire: {
          chance: 0.2,
          effect: { disclosure: 5, faction: { movement: 6 } },
          note: "The professor kept a second set in his desk, as professors do.",
        },
        note: "The courier is redirected. The lab receives ordinary dirt and reports ordinary findings.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 4, suspicion: 6 },
        note: "The ring is still visible from the air nine years later. People make a point of flying over it.",
      },
    ],
  },
  {
    id: "sight-tv-interrupt",
    tier: 3,
    tags: ["sighting", "crisis"],
    weight: 4,
    minDisclosure: 35,
    headline: "BROADCAST INTERRUPTED ACROSS THREE COUNTIES",
    dek: "Eleven minutes of carrier interference during the evening news. Viewers report {oddity}.",
    choices: [
      {
        label: "Blame sunspots, loudly",
        cost: { cash: 70 },
        effect: { disclosure: -4 },
        note: "A Weather Bureau spokesman is very confident on the record. It is a good performance.",
      },
      {
        label: "Compensate the station owner",
        cost: { cash: 140 },
        effect: { disclosure: -6, faction: { mj12: 3 } },
        note: "He accepts a new transmitter and an understanding, and never mentions it again.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 7, faction: { movement: 7 } },
        note: "Somebody recorded the audio off their set. It circulates on tape for decades.",
      },
    ],
  },
  {
    id: "sight-astronomer",
    tier: 2,
    tags: ["sighting"],
    weight: 5,
    headline: "OBSERVATORY LOGS UNEXPLAINED TRANSIT",
    dek: "A working astronomer with an unimpeachable reputation has an object on a plate and no explanation for it. He is not the sort to be talked out of things.",
    choices: [
      {
        label: "Offer him a research grant",
        cost: { cash: 165 },
        effect: { disclosure: -5, faction: { movement: -3 } },
        note: "A generous endowment, an interesting new problem, and the plate quietly stops being his priority.",
      },
      {
        label: "Corrupt the plate archive",
        cost: { cash: 75 },
        effect: { disclosure: -3 },
        backfire: {
          chance: 0.24,
          effect: { disclosure: 6, faction: { movement: 6 } },
          note: "He noticed. He is now considerably more interested than he was.",
        },
        note: "A night janitor with new debts leaves a cupboard unlocked.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 5 },
        note: "He publishes. It is careful, sober, and impossible to dismiss, which is the worst combination.",
      },
    ],
  },
  {
    id: "sight-police-pursuit",
    tier: 2,
    tags: ["sighting"],
    weight: 6,
    needsRoute: true,
    headline: "DEPUTY PURSUES OBJECT FOR SEVENTY MILES",
    dek: "A patrol car followed {object} across two county lines before losing it. The radio log is verbatim and it is very hard to read as anything else.",
    choices: [
      {
        label: "Reassign the deputy generously",
        cost: { cash: 80 },
        effect: { disclosure: -3, suspicion: -5 },
        note: "A promotion, a transfer, and a strong hint. He takes all three.",
      },
      {
        label: "Have the log misfiled",
        cost: { cash: 50 },
        effect: { disclosure: -2 },
        backfire: {
          chance: 0.18,
          effect: { disclosure: 4 },
          note: "The dispatcher had already read it to a reporter over the phone.",
        },
        note: "It goes into a box in a basement and is not found for thirty years.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 4, suspicion: 5 },
        note: "He tells it well, and he tells it for the rest of his life.",
      },
    ],
  },
  {
    id: "sight-mass-school",
    tier: 3,
    tags: ["sighting"],
    weight: 4,
    needsRoute: true,
    headline: "SCHOOLCHILDREN DESCRIBE IDENTICAL CRAFT",
    dek: "Sixty-two pupils at a school near {place}, separated and asked to draw what they saw. The drawings agree, including details none of them could have coordinated.",
    choices: [
      {
        label: "Discredit the headmaster",
        cost: { cash: 100 },
        effect: { disclosure: -4, faction: { movement: -4 } },
        backfire: {
          chance: 0.3,
          effect: { disclosure: 7, faction: { movement: 9 } },
          note: "Going after a schoolmaster over children's drawings plays extremely badly.",
        },
        note: "A question of his competence is raised, and the story becomes about him instead.",
      },
      {
        label: "Do nothing and let them be children",
        effect: { disclosure: 3, faction: { nordic: 5, movement: 3 } },
        note: "You leave it alone. The Nordics note, approvingly, that you left it alone.",
      },
      {
        label: "Wipe the schoolyard",
        cost: { cash: 190 },
        effect: { disclosure: -7, suspicion: -6, faction: { nordic: -10, movement: -3 } },
        note: "Sixty-two children lose an afternoon. It works perfectly, and the Nordics hear about it.",
      },
    ],
  },
  {
    id: "sight-press-syndication",
    tier: 3,
    tags: ["sighting"],
    weight: 5,
    minDisclosure: 30,
    headline: "{paper} RUNS SERIES ON THE SIGHTINGS",
    dek: "Six parts, syndicated to two hundred papers. The reporter is thorough, sceptical in tone, and entirely correct.",
    choices: [
      {
        label: "Buy the syndicate",
        cost: { cash: 260 },
        effect: { disclosure: -9, faction: { mj12: 4 } },
        note: "An investment group acquires a controlling interest. Part four never runs.",
      },
      {
        label: "Give the reporter a better story",
        cost: { cash: 120 },
        effect: { disclosure: -5, faction: { movement: -4 } },
        note: "A genuine political scandal is handed to him gift-wrapped. He drops everything for it.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 8, faction: { movement: 9 } },
        note: "It wins a prize. The reporter writes the book next, and the book is worse for you.",
      },
    ],
  },
  {
    id: "sight-quiet-week",
    tier: 1,
    tags: ["sighting", "boon"],
    weight: 6,
    headline: "NOTHING IN THE PAPERS THIS WEEK",
    dek: "A hurricane in the Gulf, a senator's divorce, and a pennant race have taken every column inch in the country.",
    choices: [
      {
        label: "Run everything, hard, while nobody is looking",
        effect: { suspicionAll: 6, cash: 90 },
        note: "Three nights of maximum tempo under perfect cover. It costs you in suspicion and pays you in tonnage.",
      },
      {
        label: "Use the lull to cool off",
        effect: { suspicionAll: -14, disclosure: -3 },
        note: "You sit still while the country is distracted. The meters unwind nicely.",
      },
    ],
  },
  {
    id: "sight-hoax-cover",
    tier: 1,
    tags: ["sighting", "boon"],
    weight: 7,
    headline: "HOAX EXPOSED AT {town}",
    dek: "{hoaxer} has admitted to the whole business. Every genuine report in the region is now suspect by association.",
    choices: [
      {
        label: "Amplify the debunking",
        cost: { cash: 40 },
        effect: { disclosure: -6, suspicionAll: -8, faction: { movement: -6 } },
        note: "You make sure the confession gets ten times the coverage the sighting did.",
      },
      {
        label: "Take the free cover and say nothing",
        effect: { disclosure: -3, suspicionAll: -4 },
        note: "It does its work on its own. No sense paying for weather you already have.",
      },
    ],
  },
  {
    id: "sight-blue-book",
    tier: 2,
    tags: ["sighting", "human"],
    weight: 6,
    headline: "BLUE BOOK OPENS A CASE FILE ON {place}",
    dek: "An investigator has been assigned, given a per diem, and told to be thorough. He intends to be.",
    choices: [
      {
        label: "Have him reassigned",
        cost: { cash: 90 },
        effect: { disclosure: -4, faction: { mj12: -3 } },
        note: "A more urgent case appears in Alaska. He is on a transport by Friday.",
      },
      {
        label: "Give him a tidy answer",
        cost: { cash: 55 },
        effect: { disclosure: -3, suspicion: -4 },
        note: "Swamp gas, a temperature inversion, and a plausible aircraft. He files it 'Identified' with relief.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 4, suspicion: 4 },
        note: "He files it 'Unknown', which is a word the Air Force hates seeing in its own paperwork.",
      },
    ],
  },
  {
    id: "sight-photograph-analysis",
    tier: 3,
    tags: ["sighting"],
    weight: 4,
    minDisclosure: 40,
    headline: "NAVY LAB AUTHENTICATES THE NEGATIVES",
    dek: "Photogrammetric analysis puts the object at ninety feet across and a mile out. The report was not supposed to leave the building.",
    choices: [
      {
        label: "Have MJ-12 suppress the report",
        cost: { cash: 210, standing: 4 },
        effect: { disclosure: -9, faction: { mj12: -6 } },
        note: "It is reclassified twice in a week and ceases, administratively, to exist.",
      },
      {
        label: "Commission a rival analysis",
        cost: { cash: 120 },
        effect: { disclosure: -5 },
        backfire: {
          chance: 0.26,
          effect: { disclosure: 6 },
          note: "The rival lab confirms the first one, at length, in public.",
        },
        note: "A second lab finds the methodology wanting. Two experts now disagree, which is enough.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 10, faction: { movement: 10, federation: -5 } },
        note: "A government laboratory has now certified you as real, on paper, with a stamp.",
      },
    ],
  },
  {
    id: "sight-nightwatch",
    tier: 1,
    tags: ["sighting"],
    weight: 8,
    needsRoute: true,
    headline: "SOMETHING CROSSED THE MOON AT {place}",
    dek: "{witness} watched a silhouette pass the lunar disc twice in an hour. A small item, page eleven, below the fold.",
    choices: [
      {
        label: "Nothing worth spending on",
        effect: { disclosure: 1, suspicion: 2 },
        note: "It is genuinely too small to matter. You let it go.",
      },
      {
        label: "Shift the corridor two counties east",
        cost: { cash: 25 },
        effect: { suspicion: -8 },
        note: "A small routing change. The observers get their sky back and you get your quiet.",
      },
    ],
  },
  {
    id: "sight-fisherman",
    tier: 1,
    tags: ["sighting"],
    weight: 7,
    needsRoute: true,
    headline: "OBJECT SEEN ENTERING WATER OFF {place}",
    dek: "Two men on a boat watched {object} go into the water without slowing. They waited an hour. It did not come back up.",
    choices: [
      {
        label: "Salvage the site before anyone else",
        cost: { cash: 60 },
        effect: { disclosure: -2, cash: 40 },
        note: "You recover what was dropped and leave the seabed looking untouched.",
      },
      {
        label: "Let the Navy find nothing",
        effect: { disclosure: 2, suspicion: 3 },
        note: "They drag for a week, find silt, and issue a statement nobody believes.",
      },
    ],
  },
  {
    id: "sight-airport-tower",
    tier: 2,
    tags: ["sighting"],
    weight: 6,
    needsRoute: true,
    headline: "CONTROL TOWER HOLDS OBJECT FOR HALF AN HOUR",
    dek: "Visual and radar, confirmed by three controllers and a landing crew. The tower log is signed by all of them.",
    choices: [
      {
        label: "Buy the log",
        cost: { cash: 100 },
        effect: { disclosure: -5 },
        note: "The page is removed and the binder reassembled. The controllers are told they were mistaken.",
      },
      {
        label: "Let the CAA handle it",
        effect: { disclosure: 3, suspicion: 4, faction: { mj12: 2 } },
        note: "The inspectors arrive, argue for two days, and file it under a heading that means nothing.",
      },
      {
        label: "Wipe the tower crew",
        cost: { cash: 155 },
        effect: { disclosure: -7, suspicion: -5, faction: { nordic: -5 } },
        note: "Four men lose an evening and gain a headache. The log now describes a weather balloon.",
      },
    ],
  },
  {
    id: "sight-magazine-cover",
    tier: 3,
    tags: ["sighting"],
    weight: 4,
    minDisclosure: 38,
    headline: "NATIONAL MAGAZINE PUTS IT ON THE COVER",
    dek: "Full colour, eight pages inside, and a circulation of five million. The tone is not hostile, which is worse.",
    choices: [
      {
        label: "Buy the back cover for a year",
        cost: { cash: 190 },
        effect: { disclosure: -6, faction: { mj12: 3 } },
        note: "An advertiser of that size gets a hearing on editorial direction. The follow-up never runs.",
      },
      {
        label: "Leak a spectacular fake to the same editor",
        cost: { cash: 145 },
        effect: { disclosure: -7, faction: { movement: -6 } },
        backfire: {
          chance: 0.3,
          effect: { disclosure: 9, faction: { movement: 10 } },
          note: "They authenticated it before printing, traced the source, and made that the story.",
        },
        note: "They run it, it collapses publicly, and the magazine will not touch the subject again.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 9, faction: { movement: 9 } },
        note: "Five million households. The subject stops being a rural curiosity this month.",
      },
    ],
  },
  {
    id: "sight-contrail",
    tier: 1,
    tags: ["sighting"],
    weight: 8,
    needsRoute: true,
    headline: "STRANGE TRAIL PHOTOGRAPHED OVER {place}",
    dek: "A vapour trail that turns ninety degrees. Printed small, but printed.",
    choices: [
      {
        label: "Adjust the drive trim",
        cost: { cash: 35 },
        effect: { suspicion: -7, disclosure: -1 },
        note: "A minor tuning pass. It stops leaving a noise anyone can photograph.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 2, suspicion: 3 },
        note: "Aviation enthusiasts argue about it in letters columns for a month.",
      },
    ],
  },
  {
    id: "sight-military-witness",
    tier: 3,
    tags: ["sighting", "human"],
    weight: 5,
    minDisclosure: 30,
    headline: "DECORATED OFFICER GOES ON THE RECORD",
    dek: "A man with a war record, a security clearance and nothing to gain has given a signed statement to {paper}.",
    choices: [
      {
        label: "Threaten his pension",
        cost: { cash: 60 },
        effect: { disclosure: -4, faction: { mj12: -5, movement: 4 } },
        backfire: {
          chance: 0.35,
          effect: { disclosure: 8, faction: { movement: 12 } },
          note: "He has a lawyer, a copy of everything, and now a grievance.",
        },
        note: "It is ugly and it works. He withdraws the statement and stops taking calls.",
      },
      {
        label: "Recruit him instead",
        cost: { cash: 175 },
        effect: { disclosure: -6, faction: { mj12: 6 } },
        note: "He is offered a consultancy at a salary that answers all his questions. He accepts.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 8, faction: { movement: 10 } },
        note: "He is credible, sober, and unshakeable, and he will testify to Congress in due course.",
      },
    ],
  },
  {
    id: "sight-crop-circle",
    tier: 1,
    tags: ["sighting", "boon"],
    weight: 6,
    kinds: ["ranch", "town", "anomaly"],
    headline: "GEOMETRIC PATTERN APPEARS IN FIELD AT {place}",
    dek: "Ninety feet across, laid down overnight, and quite beautiful. The farmer is charging admission.",
    choices: [
      {
        label: "Lean into it — it is free advertising",
        effect: { disclosure: 3, cash: 110, faction: { nordic: 4 } },
        note: "Tourist traffic triples in the county. Charter bookings follow it.",
      },
      {
        label: "Have it ploughed under tonight",
        cost: { cash: 45 },
        effect: { disclosure: -3, suspicion: -6 },
        note: "It is gone before the wire photographer arrives. The farmer is compensated for the crop.",
      },
    ],
  },
];
