// Slot vocabulary. Event templates carry {tokens}; these pools fill them, so
// the same authored event reads differently every time it surfaces. The pools
// are deliberately period-flavoured — mid-century American local press.

export const VOCAB: Record<string, readonly string[]> = {
  witness: [
    "a county sheriff",
    "two seminary students",
    "a crop duster pilot",
    "the night shift at a grain elevator",
    "a Greyhound driver and eleven passengers",
    "a widowed schoolteacher",
    "a Boy Scout troop and their scoutmaster",
    "three off-duty state troopers",
    "a drive-in projectionist",
    "the entire congregation of a Baptist revival",
    "a fire lookout",
    "a rural mail carrier",
    "an insurance adjuster from out of state",
    "a family of six returning from a funeral",
    "a lighthouse keeper",
    "the local high school football team",
    "a pair of honeymooners",
    "a retired naval officer",
    "a woman hanging washing at four in the morning",
    "two brothers running a trotline",
    "a radio DJ mid-broadcast",
    "a bowling league on the way home",
    "an amateur astronomer with a good telescope",
    "the county coroner",
    "a travelling encyclopaedia salesman",
    "a switchboard operator who logged every call",
    "a diner cook and four customers",
    "a girl of nine and her grandmother",
    "the pit crew at a dirt track",
    "a Pinkerton man on an unrelated job",
  ],

  official: [
    "the county sheriff",
    "an Air Force public information officer",
    "the state police commissioner",
    "a congressman up for re-election",
    "the mayor",
    "a Blue Book investigator",
    "the base commander at the nearest field",
    "a Justice Department attaché",
    "the state agriculture commissioner",
    "a university physics professor on retainer",
    "the regional FBI field office",
    "a Civil Aeronautics inspector",
    "the National Guard adjutant",
    "a Senate staffer with a hobby interest",
    "the coroner's office",
    "a retired general on a magazine payroll",
    "the district attorney",
    "a Weather Bureau spokesman",
  ],

  oddity: [
    "every clock in the building ran ninety seconds fast afterward",
    "the grass beneath was found woven flat in a clockwise spiral",
    "all the dogs in the township refused to go outside for a week",
    "three cows were later found standing on a barn roof, unhurt",
    "the film came back exposed except for a single perfect frame",
    "a smell of ozone and burnt cinnamon lingered for two days",
    "the well water ran warm and faintly sweet",
    "every radio within a mile picked up the same six-note phrase",
    "the snow melted in a ring forty feet across and nowhere else",
    "a man's wristwatch ran backwards for the rest of his life",
    "the church bell rang itself at 3:14 a.m.",
    "birds circled the spot for eleven days and then stopped at once",
    "the topsoil tested sterile to a depth of one foot",
    "two people described the same dream that night, independently",
    "the telephone poles hummed a minor third",
    "a stand of pines grew a foot in a fortnight and then died",
    "the pond froze in August",
    "a cat came home three weeks later, dry, fed, and pregnant",
    "the compass in the truck pointed south for a month",
    "photographs taken there develop with an extra person at the edge",
    "the cattle would not cross that pasture again, ever",
    "a boy's nosebleed would not stop until he left the county",
    "the fence wire was found cut cleanly, from the inside",
    "everyone present lost the same forty minutes",
    "the road surface was warm to the touch at dawn",
    "a hen laid an egg with no yolk and a perfect sphere inside",
    "static on the party line spelled something in Morse, twice",
    "the corn grew in that year, but nothing would eat it",
    "the barn cats all went deaf on the same night",
    "a sound like a cello played underwater came from the ground",
  ],

  paper: [
    "The Evening Star",
    "The Daily Bulletin",
    "The County Register",
    "The Morning Herald",
    "The Sentinel",
    "The Gazette & Advertiser",
    "The Tribune",
    "The Weekly Clarion",
    "The Press-Democrat",
    "The Journal-Standard",
    "The Courier",
    "The Free Press",
    "The Times-Picayune",
    "The Chronicle",
    "The Post-Dispatch",
    "The Examiner",
    "The Plain Dealer",
    "The Beacon-News",
    "The Statesman",
    "The Item",
  ],

  creature: [
    "a tall figure with no face",
    "something with a wingspan and red eyes",
    "three small silver men",
    "a shape that walked like a man and hinged wrongly",
    "a dog that stood up",
    "a hooded thing that hissed and floated",
    "a woman in white who left no prints",
    "something the size of a barn owl and the shape of nothing",
    "a grey child with black eyes",
    "a figure in a pressed dark suit who did not blink",
    "a thing that was mostly legs",
    "an old man nobody in the county recognised",
    "a shape wearing a state trooper's uniform, badly",
    "something that reflected the headlights like a road sign",
    "a pale swimmer a mile from any water",
    "a creature that apologised before leaving",
  ],

  object: [
    "a disc the colour of a nickel",
    "an orange light that split into three",
    "a black triangle with lights at each corner",
    "a cigar-shaped craft two hundred feet long",
    "a formation of nine lights in a shallow V",
    "a silver sphere that hovered and dropped",
    "something like a hubcap on edge",
    "a cluster of small lights that moved as one",
    "a domed object with a rim of windows",
    "a shape that was only visible where the stars were missing",
    "a rotating band of red and green",
    "an object that made no sound at all, which was the worst part",
    "a light that answered when the flashlight was blinked at it",
    "two objects that merged and became brighter",
    "a thing that hung motionless for forty minutes and then was not there",
    "a wedge that trailed a green wake",
    "a pale disc that outran a P-51",
    "a shape described identically by people who never met",
  ],

  town: [
    "Beaver Falls",
    "New Harmony",
    "Bishopville",
    "Coldwater",
    "Antioch",
    "Marion Junction",
    "Pleasant Grove",
    "Sulphur Springs",
    "Elk Creek",
    "Athens",
    "Bethel",
    "Rocky Ford",
    "Cedar Bluff",
    "Wilmot",
    "Bonne Terre",
    "Cactus Flats",
    "Hidalgo",
    "Two Rivers",
  ],

  hoaxer: [
    "a college fraternity",
    "a hardware store owner with a weather balloon",
    "two teenagers and a pie tin",
    "a struggling motel proprietor",
    "the local Jaycees",
    "a man who has confessed to four previous hoaxes",
    "an art student with a very good airbrush",
    "the chamber of commerce, off the record",
  ],

  believer: [
    "a retired colonel with a mailing list",
    "a housewife who has filed 400 FOIA requests",
    "the editor of a mimeographed newsletter",
    "a physics graduate student with tenure ambitions",
    "a radio host with a national syndication deal",
    "a Catholic priest who will not be dissuaded",
    "a millionaire with a foundation and a grudge",
    "a schoolteacher who kept every clipping since 1947",
  ],
};

