import type { EventDef } from "../types";

// The strangeness. Time slips, cargo that arrives wrong, cryptids, thin places,
// and the things that happen when you run a logistics operation through a
// planet that has its own opinions. These are the ones worth replaying for.

export const WEIRD: EventDef[] = [
  {
    id: "weird-timeslip",
    tier: 3,
    tags: ["weird", "crisis"],
    weight: 6,
    needsRoute: true,
    headline: "A CRAFT ARRIVES ELEVEN YEARS EARLY",
    dek: "It left {place} on schedule. It arrived at the terminal on the correct date in the wrong decade, with a crew who had not aged and cargo that had.",
    choices: [
      {
        label: "Debrief the crew and file it",
        cost: { cash: 60 },
        effect: { standing: 3, disclosure: -2 },
        note: "Statements taken, discrepancies noted, everyone reassigned to different shifts. It happens.",
      },
      {
        label: "Sell the displaced cargo as an antiquity",
        effect: { cash: 210, standing: -5, disclosure: 4 },
        note: "Eleven years of provenance out of nowhere. The buyer does not ask and you do not explain.",
      },
      {
        label: "Send it back through deliberately",
        cost: { cash: 130 },
        effect: { disclosure: -6, standing: 6 },
        backfire: {
          chance: 0.35,
          effect: { loseCraft: true, disclosure: 5 },
          note: "It did not come back this time. Neither did anyone aboard.",
        },
        note: "A controlled reinsertion closes the loop. The paperwork now agrees with itself.",
      },
    ],
  },
  {
    id: "weird-salem",
    tier: 3,
    tags: ["weird"],
    weight: 5,
    needsRoute: true,
    headline: "A CATTLE HAULER HAS DROPPED INTO 1692",
    dek: "Wormhole misfire on the eastern leg. The craft is intact, the crew are unharmed, and a Massachusetts village is currently watching them.",
    choices: [
      {
        label: "Extract immediately, cost no object",
        cost: { cash: 200 },
        effect: { disclosure: -4, standing: 4 },
        note: "Out within the hour. The village adds it to a list of grievances that will not go well for anyone.",
      },
      {
        label: "Extract the crew, abandon the hull",
        cost: { cash: 70 },
        effect: { loseCraft: true, disclosure: 2 },
        note: "The crew come home. The hull stays, buried, and will be found by a contractor in 1974.",
      },
      {
        label: "Let them work out their own way back",
        effect: { disclosure: 8, faction: { federation: -10 }, standing: -8 },
        note: "They manage it in four days. The Federation's temporal office would like a word about the other three.",
      },
    ],
  },
  {
    id: "weird-cargo-alive",
    tier: 2,
    tags: ["weird"],
    weight: 6,
    needsRoute: true,
    races: ["grey", "mantid"],
    headline: "THE CARGO HAS WOKEN UP",
    dek: "Something in the hold has come round early, and it is not any of the things that were loaded at {place}.",
    choices: [
      {
        label: "Sedate and continue",
        cost: { cash: 45 },
        effect: { disclosure: 1 },
        note: "Handled routinely. It goes into the manifest as breakage and nobody looks closely.",
      },
      {
        label: "Set it down somewhere empty",
        effect: { suspicion: 8, disclosure: 3, faction: { nordic: 5 } },
        note: "You put it down in open country and leave. It walks off north and is somebody's legend by Tuesday.",
      },
      {
        label: "Study it",
        cost: { cash: 90 },
        effect: { cash: 180, faction: { mantid: 8 }, spawnSpecimens: 2 },
        note: "The Directorate is extremely interested in what came aboard and where it came aboard from.",
      },
    ],
  },
  {
    id: "weird-second-moon",
    tier: 3,
    tags: ["weird"],
    weight: 4,
    headline: "ASTRONOMERS REPORT A SECOND OBJECT IN ORBIT",
    dek: "Small, dark, and in a retrograde orbit nothing natural should occupy. It is not one of yours. Nobody will say whose it is.",
    choices: [
      {
        label: "Investigate it",
        cost: { cash: 160 },
        effect: { standing: 6, cash: 120, disclosure: 2 },
        note: "A derelict, very old, and not of any registered origin. Salvage rights are yours by default.",
      },
      {
        label: "Report it to the Federation",
        effect: { standing: 12, faction: { federation: 8 } },
        note: "They already knew. They are pleased you told them anyway, which is the entire point of telling them.",
      },
      {
        label: "Shoot it down before anyone photographs it",
        cost: { cash: 190 },
        effect: { disclosure: -5, standing: -10, faction: { federation: -12 } },
        backfire: {
          chance: 0.3,
          effect: { disclosure: 10, suspicionAll: 12 },
          note: "It came down over a populated county in a great many burning pieces.",
        },
        note: "It deorbits over open ocean. The astronomers conclude they made an error.",
      },
    ],
  },
  {
    id: "weird-mothman",
    tier: 2,
    tags: ["weird"],
    weight: 6,
    kinds: ["town", "anomaly"],
    headline: "SOMETHING IS FOLLOWING THE ROUTE",
    dek: "{creature} has been reported at {place} on eleven consecutive nights, always on your corridor, always ahead of the craft.",
    choices: [
      {
        label: "Reroute around it",
        cost: { cash: 50 },
        effect: { suspicion: -10, disclosure: -2 },
        note: "You go around. The sightings stop the same week, which raises questions nobody wants answered.",
      },
      {
        label: "Try to make contact",
        cost: { cash: 80 },
        effect: { faction: { mantid: 6 }, spawnSpecimens: 2, disclosure: 3 },
        backfire: {
          chance: 0.3,
          effect: { loseCraft: true, disclosure: 6 },
          note: "Contact was made. The craft came back empty and the recorder had been switched off from inside.",
        },
        note: "It permits an approach. What is learned is filed under a heading with no other entries.",
      },
      {
        label: "Carry on and ignore it",
        effect: { disclosure: 5, suspicion: 8, faction: { movement: 5 } },
        note: "The town names it. In thirteen months there will be a bridge collapse and the name will stick.",
      },
    ],
  },
  {
    id: "weird-dinosaur",
    tier: 2,
    tags: ["weird", "boon"],
    weight: 4,
    needsRoute: true,
    headline: "THE GATE HAS DELIVERED SOMETHING PREHISTORIC",
    dek: "Nine tons of it, sedated, in a hangar, and breathing. The manifest says forty crates of soil cores.",
    choices: [
      {
        label: "Sell it to a museum world",
        effect: { cash: 320, standing: -4, faction: { mantid: 5 } },
        note: "A collector three systems out pays extravagantly and asks no questions about provenance.",
      },
      {
        label: "Send it back where it came from",
        cost: { cash: 110 },
        effect: { standing: 8, faction: { federation: 6 } },
        note: "Returned to the correct stratum. The Federation's ecology office writes to thank you.",
      },
      {
        label: "Release it into the Everglades",
        effect: { disclosure: 9, suspicion: 14, cash: 40, faction: { movement: 8, nordic: -10 } },
        note: "An extremely bad decision, taken quickly, for a small amount of money.",
      },
    ],
  },
  {
    id: "weird-doubles",
    tier: 3,
    tags: ["weird"],
    weight: 5,
    needsRoute: true,
    headline: "THE CREW HAVE COME BACK TWICE",
    dek: "Two identical craft, two identical crews, one departure record. Both sets insist they are the originals and both are correct.",
    choices: [
      {
        label: "Keep both, quietly",
        effect: { grantCraft: "scout", disclosure: 3, standing: -6 },
        note: "You now have an extra hull and an extra crew that do not officially exist. Useful. Unsettling.",
      },
      {
        label: "Report it and accept the audit",
        effect: { standing: 10, disclosure: -3, cash: -60 },
        note: "The Federation resolves the duplication by a method they decline to describe. One set remains.",
      },
      {
        label: "Send one set through the gate again",
        cost: { cash: 70 },
        effect: { disclosure: -2 },
        backfire: {
          chance: 0.4,
          effect: { loseCraft: true, standing: -8, disclosure: 5 },
          note: "Three came back this time. You stopped the experiment there.",
        },
        note: "The duplication reverses cleanly. Nobody speaks about it again.",
      },
    ],
  },
  {
    id: "weird-hum",
    tier: 1,
    tags: ["weird"],
    weight: 7,
    needsRoute: true,
    headline: "A TOWN CANNOT SLEEP FOR THE HUM",
    dek: "A low tone at the edge of hearing, at {place}, every night since your corridor opened. {oddity}.",
    choices: [
      {
        label: "Shift the drive frequency",
        cost: { cash: 55 },
        effect: { suspicion: -9, disclosure: -2 },
        note: "A retune. The hum stops and the town sleeps and nobody ever learns why either happened.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 3, suspicion: 6 },
        note: "A university sends someone with instruments. They record it, publish it, and cannot explain it.",
      },
    ],
  },
  {
    id: "weird-thin-place",
    tier: 2,
    tags: ["weird", "boon"],
    weight: 5,
    kinds: ["anomaly", "landmark"],
    headline: "THE APERTURE AT {place} HAS WIDENED",
    dek: "It is holding open on its own, stable, and considerably larger than the survey said it could be.",
    choices: [
      {
        label: "Exploit it hard while it lasts",
        effect: { cash: 200, disclosure: 5, suspicion: 10 },
        note: "Three weeks of nearly free transit. It closes without warning and takes a cargo with it.",
      },
      {
        label: "Survey it properly first",
        cost: { cash: 90 },
        effect: { standing: 6, unlockSite: "random", faction: { mantid: 5 } },
        note: "Careful work. It maps to another aperture nobody had charted, which is now yours.",
      },
      {
        label: "Seal it",
        cost: { cash: 120 },
        effect: { standing: 8, suspicion: -12, faction: { federation: 6 } },
        note: "Closed and capped. An unstable aperture is a licence violation waiting to happen.",
      },
    ],
  },
  {
    id: "weird-nobody-remembers",
    tier: 2,
    tags: ["weird"],
    weight: 5,
    needsRoute: true,
    headline: "AN ENTIRE COUNTY HAS FORGOTTEN A TUESDAY",
    dek: "Not your doing. Nobody has claimed it. Twelve thousand people cannot account for a day and the newspapers for that date do not exist.",
    choices: [
      {
        label: "Take the credit with the Federation",
        effect: { standing: 8, disclosure: -6 },
        backfire: {
          chance: 0.35,
          effect: { standing: -14, faction: { federation: -10 } },
          note: "They asked for the operational record of a wipe you did not perform.",
        },
        note: "You file it as a sanctioned suppression. It reads beautifully in the quarterly return.",
      },
      {
        label: "Find out who did it",
        cost: { cash: 140 },
        effect: { standing: 4, faction: { mantid: 6 }, disclosure: -3 },
        note: "A Directorate deep-cover programme, unlisted. They are mildly embarrassed to be found.",
      },
      {
        label: "Leave it alone",
        effect: { disclosure: -2 },
        note: "Not your county, not your Tuesday, not your problem. The meters like it either way.",
      },
    ],
  },
  {
    id: "weird-cattle-return",
    tier: 2,
    tags: ["weird"],
    weight: 6,
    races: ["grey"],
    kinds: ["ranch"],
    headline: "THE HERD HAS COME BACK",
    dek: "Two hundred head taken from {place} last season have reappeared in the same pasture overnight. They are healthy, calm, and marked.",
    choices: [
      {
        label: "Retrieve them again quickly",
        cost: { cash: 40 },
        effect: { cash: 130, suspicion: 12, disclosure: 4 },
        note: "A second harvest from the same stock. The rancher's account of the year is now unpublishable.",
      },
      {
        label: "Leave them and abandon the site",
        effect: { suspicion: -16, disclosure: -3, faction: { nordic: 6 } },
        note: "You never work that pasture again. The rancher tells the story for forty years and is believed by nobody.",
      },
      {
        label: "Work out who returned them",
        cost: { cash: 100 },
        effect: { faction: { nordic: 10, mantid: 4 }, standing: 3 },
        note: "The Nordics did. They consider the practice wasteful and have been quietly reversing it.",
      },
    ],
  },
  {
    id: "weird-mirror-crew",
    tier: 3,
    tags: ["weird", "crisis"],
    weight: 4,
    needsRoute: true,
    minDisclosure: 30,
    headline: "THE CREW ARE SPEAKING BACKWARDS",
    dek: "All four of them, fluently, and they do not appear to know they are doing it. The flight recorder plays correctly when reversed.",
    choices: [
      {
        label: "Ground them and treat it",
        cost: { cash: 95 },
        effect: { standing: 4, disclosure: -2 },
        note: "Six weeks off the roster. Three recover fully. The fourth is reassigned to a desk.",
      },
      {
        label: "Keep flying them",
        effect: { cash: 90, disclosure: 5, faction: { nordic: -8 } },
        note: "They fly perfectly well. Ground crews have started refusing to load their craft.",
      },
      {
        label: "Hand them to the Directorate",
        effect: { faction: { mantid: 12 }, cash: 140, standing: -3 },
        note: "The Mantids take all four and pay generously. You do not ask what for.",
      },
    ],
  },
  {
    id: "weird-lights-answer",
    tier: 2,
    tags: ["weird"],
    weight: 6,
    kinds: ["anomaly"],
    headline: "THE LIGHTS AT {place} ARE ANSWERING",
    dek: "They have begun repeating your craft's approach signals back, accurately, before the craft transmits them.",
    choices: [
      {
        label: "Open a channel",
        cost: { cash: 110 },
        effect: { faction: { mantid: 8 }, standing: 5, unlockSite: "random" },
        backfire: {
          chance: 0.25,
          effect: { disclosure: 7, suspicion: 12 },
          note: "Whatever answered was considerably louder than expected, and not only on your frequency.",
        },
        note: "Something is there and it has been there a long time. It gives you a chart.",
      },
      {
        label: "Change the signals",
        cost: { cash: 40 },
        effect: { suspicion: -6 },
        note: "New codes weekly. The echo stops. You do not know whether it stopped or merely stopped answering.",
      },
      {
        label: "Stop using the site",
        effect: { suspicion: -14, cash: -50 },
        note: "You close the approach entirely. It costs throughput and it costs nothing else, which is the point.",
      },
    ],
  },
  {
    id: "weird-vanished-town",
    tier: 4,
    tags: ["weird", "crisis"],
    weight: 3,
    minDisclosure: 45,
    headline: "A SETTLEMENT IS NO LONGER THERE",
    dek: "Forty-one residents at {town}. The buildings remain, the meals are on the tables, and the people are not anywhere.",
    choices: [
      {
        label: "Report it and cooperate fully",
        effect: { standing: 12, disclosure: 6, faction: { federation: 8 } },
        note: "A full Federation investigation. It was not you. Proving that takes three months and it is worth it.",
      },
      {
        label: "Stage it as a natural disaster",
        cost: { cash: 210 },
        effect: { disclosure: -8, standing: -10, faction: { nordic: -12 } },
        backfire: {
          chance: 0.3,
          effect: { disclosure: 14, standing: -16 },
          note: "There was no weather that night and every meteorologist in the country knows it.",
        },
        note: "A gas main, a fire, an evacuation that is never quite documented. It holds.",
      },
      {
        label: "Search for them yourself",
        cost: { cash: 150 },
        effect: { standing: 6, faction: { nordic: 8 }, disclosure: 3 },
        note: "You find eleven of them, alive, four hundred miles away, and returned with nothing to say.",
      },
    ],
  },
  {
    id: "weird-recurring-dream",
    tier: 2,
    tags: ["weird"],
    weight: 5,
    needsRoute: true,
    headline: "EVERYONE UNDER THE CORRIDOR IS HAVING THE SAME DREAM",
    dek: "Reported independently across four counties beneath your route. It involves a room, a table, and a decision. {oddity}.",
    choices: [
      {
        label: "Damp the drive's bleed",
        cost: { cash: 100 },
        effect: { suspicion: -12, disclosure: -3, faction: { nordic: 5 } },
        note: "Shielding fitted fleet-wide. The dreams stop within a fortnight.",
      },
      {
        label: "Study the effect",
        cost: { cash: 70 },
        effect: { faction: { mantid: 10 }, cash: 160, disclosure: 4 },
        note: "The Directorate is very interested indeed in unintentional broadcast of that kind.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 4, suspicion: 5, faction: { movement: 5 } },
        note: "A psychiatrist collects two hundred accounts and writes a paper that will not be believed for decades.",
      },
    ],
  },
  {
    id: "weird-gravity",
    tier: 2,
    tags: ["weird"],
    weight: 5,
    needsRoute: true,
    headline: "OBJECTS ARE FALLING UPWARD AT {place}",
    dek: "A twenty-yard patch beneath the approach. It is not dramatic — a dropped hat goes up instead of down — and it is entirely reproducible.",
    choices: [
      {
        label: "Correct the drive alignment",
        cost: { cash: 85 },
        effect: { suspicion: -10, disclosure: -2 },
        note: "Realigned. The patch decays over a month and the local children are disappointed.",
      },
      {
        label: "Fence it off and charge admission",
        effect: { cash: 140, disclosure: 6, suspicion: 8 },
        note: "A roadside attraction with a gift shop. Absurd, lucrative, and it hides the cause in plain sight.",
      },
      {
        label: "Report it to the Federation",
        effect: { standing: 7, cash: -40 },
        note: "A containment team arrives, corrects it properly, and bills you for the callout.",
      },
    ],
  },
  {
    id: "weird-broadcast",
    tier: 3,
    tags: ["weird"],
    weight: 4,
    minDisclosure: 30,
    headline: "A SIGNAL IS COMING FROM UNDER THE SITE",
    dek: "Beneath {place}, at a depth nothing should be at, something has started transmitting on a schedule.",
    choices: [
      {
        label: "Excavate",
        cost: { cash: 180 },
        effect: { cash: 260, faction: { mantid: 8 }, disclosure: 5, suspicion: 10 },
        note: "Something old and not yours. It is worth a great deal and it was, apparently, waiting.",
      },
      {
        label: "Report it and step back",
        effect: { standing: 10, faction: { federation: 8 } },
        note: "The Federation seals the site within days and does not tell you what was there.",
      },
      {
        label: "Jam it",
        cost: { cash: 90 },
        effect: { suspicion: -8, disclosure: -3 },
        backfire: {
          chance: 0.3,
          effect: { disclosure: 8, suspicion: 14 },
          note: "It increased power to compensate. It is now audible on domestic radio sets.",
        },
        note: "Suppressed at the source. Whatever it was saying, it is not saying it loudly any more.",
      },
    ],
  },
  {
    id: "weird-visitor",
    tier: 3,
    tags: ["weird"],
    weight: 4,
    headline: "SOMEONE HAS BEEN IN THE OPERATIONS ROOM",
    dek: "No entry record, no alarm, nothing taken. A chair has been moved and there is a note on the desk in your own handwriting.",
    choices: [
      {
        label: "Read the note and act on it",
        effect: { cash: 190, standing: 4, disclosure: -4 },
        backfire: {
          chance: 0.3,
          effect: { disclosure: 8, cash: -140 },
          note: "The advice was excellent and led somewhere very bad, which was presumably the intention.",
        },
        note: "It describes the next four weeks accurately. You use it. It is correct throughout.",
      },
      {
        label: "Burn it unread",
        effect: { standing: 6, disclosure: -2 },
        note: "Destroyed. You have a strong sense of having made this decision before.",
      },
      {
        label: "Hand it to the Federation",
        effect: { standing: 12, faction: { federation: 8 } },
        note: "They read it, take it, and reassign two of their own people the same week.",
      },
    ],
  },
  {
    id: "weird-perfect-run",
    tier: 1,
    tags: ["weird", "boon"],
    weight: 6,
    needsRoute: true,
    headline: "A RUN COMPLETES ITSELF",
    dek: "The craft went out empty by clerical error and came back loaded, on time, with the manifest already filled in correctly.",
    choices: [
      {
        label: "Bank it and ask nothing",
        effect: { cash: 130 },
        note: "The cargo is good. The handwriting on the manifest is nobody's. You file it and move on.",
      },
      {
        label: "Investigate",
        cost: { cash: 60 },
        effect: { standing: 5, faction: { mantid: 5 }, disclosure: -2 },
        note: "A scheduling overlap with a route that has not been built yet. The Directorate finds this fascinating.",
      },
    ],
  },
  {
    id: "weird-rain",
    tier: 1,
    tags: ["weird"],
    weight: 6,
    needsRoute: true,
    headline: "IT IS RAINING SOMETHING ELSE AT {place}",
    dek: "Fish, mostly. Some frogs. A quantity of small machined components that nobody can identify, over four square miles.",
    choices: [
      {
        label: "Recover the components before anyone else",
        cost: { cash: 55 },
        effect: { disclosure: -4, cash: 70 },
        note: "A quiet sweep at first light. The fish stay; the fish are not the problem.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 4, suspicion: 5, faction: { movement: 4 } },
        note: "A Fortean society acquires eleven of the components and photographs all of them.",
      },
    ],
  },
  {
    id: "weird-double-moon",
    tier: 2,
    tags: ["weird"],
    weight: 5,
    needsRoute: true,
    headline: "THE CORRIDOR IS RUNNING TWO MINUTES SHORT",
    dek: "Every transit, consistently, for a month. The distance has not changed. The clocks have been checked and the clocks are correct.",
    choices: [
      {
        label: "Exploit the shortcut",
        effect: { cash: 150, disclosure: 3, standing: -4 },
        note: "Two free minutes a run adds up handsomely. You do not report the discrepancy.",
      },
      {
        label: "Report it",
        effect: { standing: 9, faction: { federation: 6 } },
        note: "A survey team confirms a genuine geodesic anomaly. It is charted and named after your operation.",
      },
      {
        label: "Stop using the corridor",
        effect: { suspicion: -8, cash: -60 },
        note: "Abandoned as a precaution. You will wonder about it for the rest of the run.",
      },
    ],
  },
  {
    id: "weird-passenger",
    tier: 2,
    tags: ["weird"],
    weight: 5,
    races: ["nordic"],
    headline: "THERE IS AN EXTRA PASSENGER ON THE MANIFEST",
    dek: "Forty booked, forty-one aboard, forty disembarked. The photograph from the observation deck shows forty-one, and one of them is not looking at the view.",
    choices: [
      {
        label: "Review every tour photograph",
        cost: { cash: 75 },
        effect: { standing: 4, faction: { mantid: 6 }, disclosure: -2 },
        note: "The same figure appears in eleven previous tours, at the edge, always slightly out of focus.",
      },
      {
        label: "Say nothing to the guests",
        effect: { cash: 90, disclosure: 3, faction: { nordic: -5 } },
        note: "The season proceeds. Bookings are unaffected. The figure keeps appearing.",
      },
      {
        label: "Suspend the route",
        effect: { suspicion: -10, cash: -70, standing: 3 },
        note: "Pulled pending review. Whatever it is, it does not follow you to the other corridors.",
      },
    ],
  },
  {
    id: "weird-specimen-talks",
    tier: 3,
    tags: ["weird"],
    weight: 5,
    races: ["mantid"],
    headline: "A SPECIMEN HAS ASKED A QUESTION",
    dek: "Coherent, in context, and in a language nobody aboard had used in its presence. It is waiting for an answer.",
    choices: [
      {
        label: "Answer it",
        effect: { faction: { mantid: 12 }, goal: 2, disclosure: 3, standing: -3 },
        note: "A long conversation follows. The Directorate reclassifies the entire line upward on the strength of it.",
      },
      {
        label: "Terminate the line",
        cost: { cash: 60 },
        effect: { faction: { mantid: -8, nordic: -10 }, disclosure: -4 },
        note: "Closed out cleanly. It is the safe decision and nobody involved feels good about it.",
      },
      {
        label: "Release it where it was taken from",
        effect: { faction: { nordic: 14, mantid: -6 }, standing: 5, suspicion: 6 },
        note: "Returned to {place}. It walks home. The Nordics hear about this within the day.",
      },
    ],
  },
  {
    id: "weird-fog",
    tier: 1,
    tags: ["weird", "boon"],
    weight: 6,
    headline: "AN UNSEASONAL FOG HAS SETTLED OVER THE SECTOR",
    dek: "Six hundred miles of it, forecast by nobody, holding for a week. Visibility at ground level is under thirty feet.",
    choices: [
      {
        label: "Run everything at maximum tempo",
        effect: { cash: 180, suspicionAll: -6 },
        note: "A week of near-total cover. It is the best operating window of the year.",
      },
      {
        label: "Be suspicious of it",
        cost: { cash: 50 },
        effect: { standing: 5, faction: { nordic: 6 } },
        note: "The Nordics laid it on deliberately as a professional courtesy. Acknowledging it costs little and buys much.",
      },
    ],
  },
  {
    id: "weird-old-wreck",
    tier: 2,
    tags: ["weird", "boon"],
    weight: 5,
    headline: "A WRECK IS FOUND THAT PREDATES YOUR LICENCE",
    dek: "Buried at {place}, considerably older than any licensed operation on this planet, and of no design on file.",
    choices: [
      {
        label: "Salvage it quietly",
        cost: { cash: 90 },
        effect: { cash: 280, standing: -6, disclosure: 3 },
        note: "Stripped and sold through four intermediaries. Nobody asks and the price is extraordinary.",
      },
      {
        label: "Report the find",
        effect: { standing: 14, faction: { federation: 10, mantid: 6 } },
        note: "A significant archaeological event. Your name is on the discovery in perpetuity.",
      },
      {
        label: "Rebury it",
        effect: { suspicion: -6, disclosure: -3 },
        note: "Covered over and forgotten deliberately. Some things are less trouble underground.",
      },
    ],
  },
  {
    id: "weird-loop",
    tier: 3,
    tags: ["weird", "crisis"],
    weight: 4,
    needsRoute: true,
    minDisclosure: 35,
    headline: "TUESDAY HAS HAPPENED FOUR TIMES",
    dek: "Your operations room has four sets of logs for the same date, all in different hands, all describing slightly different nights.",
    choices: [
      {
        label: "Break the loop deliberately",
        cost: { cash: 130 },
        effect: { standing: 6, disclosure: -5 },
        backfire: {
          chance: 0.3,
          effect: { loseRoute: true, disclosure: 6 },
          note: "The loop broke and took a corridor with it. That corridor is now simply not there.",
        },
        note: "A hard stand-down until the date advances. It works, expensively.",
      },
      {
        label: "Run the same profitable day repeatedly",
        effect: { cash: 240, standing: -10, disclosure: 7 },
        note: "Four times the takings from one day's exposure. The Federation will find this in the audit.",
      },
      {
        label: "Wait it out",
        effect: { disclosure: 3, cash: -40 },
        note: "It resolves on its own by Friday. Nobody is certain how many Fridays there were.",
      },
    ],
  },
  {
    id: "weird-witness-knows",
    tier: 3,
    tags: ["weird"],
    weight: 4,
    needsRoute: true,
    minDisclosure: 25,
    headline: "A WITNESS KNEW YOUR NAME",
    dek: "{witness} at {place} addressed the crew by designation, in the correct order of seniority, and then asked after the previous operator.",
    choices: [
      {
        label: "Bring them in",
        cost: { cash: 100 },
        effect: { faction: { mantid: 8 }, spawnSpecimens: 2, disclosure: -3 },
        note: "They come willingly. They have been waiting some years and they have a great deal to say.",
      },
      {
        label: "Wipe and release",
        cost: { cash: 70 },
        effect: { disclosure: -5, faction: { nordic: -5 } },
        backfire: {
          chance: 0.3,
          effect: { disclosure: 8, faction: { movement: 8 } },
          note: "It did not take. It has never not taken before.",
        },
        note: "Standard procedure, cleanly done. They wake up on a bus with a headache.",
      },
      {
        label: "Answer the question",
        effect: { disclosure: 6, standing: -5, faction: { movement: 6, nordic: 4 } },
        note: "You tell them what happened to your predecessor. They thank you and walk away satisfied.",
      },
    ],
  },
  {
    id: "weird-quake",
    tier: 2,
    tags: ["weird"],
    weight: 6,
    needsRoute: true,
    headline: "TREMORS AT {place} WITH NO FAULT BENEATH",
    dek: "Four shocks in nine days, all shallow, all centred on open country. The Geological Survey is embarrassed: there is no fault under {place} and there never has been.",
    choices: [
      {
        label: "Damp the drive resonance",
        cost: { cash: 105 },
        effect: { suspicion: -12, disclosure: -3 },
        note: "A refit across the fleet. The ground stops ringing like a struck bell within the week.",
      },
      {
        label: "Let them blame the weapons tests",
        cost: { cash: 45 },
        effect: { disclosure: -4, faction: { mj12: -4 } },
        backfire: {
          chance: 0.25,
          effect: { disclosure: 6, faction: { mj12: -8 } },
          note: "The nearest test range was cold that fortnight and said so, in writing, to a newspaper.",
        },
        note: "A helpful official mentions underground detonations. Nobody enjoys the explanation and everybody accepts it.",
      },
      {
        label: "Ignore it",
        effect: { disclosure: 4, suspicion: 8, faction: { movement: 5 } },
        note: "A seismologist plots the epicentres. They fall along a line, and the line is your corridor.",
      },
    ],
  },
  {
    id: "weird-quake-opens",
    tier: 3,
    tags: ["weird", "boon"],
    weight: 4,
    kinds: ["ranch", "town", "anomaly", "landmark"],
    headline: "EARTHQUAKE OPENS THE GROUND AT {place}",
    dek: "A genuine one this time, and not yours. It has split a hillside and exposed something with a machined edge, forty feet down. {oddity}.",
    choices: [
      {
        label: "Get there first and strip it",
        cost: { cash: 80 },
        effect: { cash: 300, disclosure: 4, suspicion: 10 },
        backfire: {
          chance: 0.25,
          effect: { disclosure: 8, suspicion: 14, faction: { movement: 7 } },
          note: "A rescue crew was already on the slope and watched the whole recovery.",
        },
        note: "Out before dawn, hole backfilled, and a great deal of very old salvage on the books.",
      },
      {
        label: "Collapse the site and lose it",
        cost: { cash: 120 },
        effect: { disclosure: -7, suspicion: -8, standing: 4 },
        note: "A second, smaller slide closes the fissure. Whatever it was stays where it was.",
      },
      {
        label: "Report it to the Federation",
        effect: { standing: 12, faction: { federation: 8, mantid: 5 }, disclosure: -2 },
        note: "They arrive within the day, take everything, and enter your name on the find.",
      },
    ],
  },
  {
    id: "weird-cold-spot",
    tier: 1,
    tags: ["weird"],
    weight: 6,
    kinds: ["anomaly", "landmark", "town"],
    headline: "THE POND AT {place} HAS FROZEN IN AUGUST",
    dek: "Solid, eleven inches thick, in ninety-degree heat, and only that pond. {oddity}.",
    choices: [
      {
        label: "Move operations away from it",
        effect: { suspicion: -8, cash: -30 },
        note: "You give the area a wide berth. It thaws in October, on schedule, as though nothing happened.",
      },
      {
        label: "Sample the ice",
        cost: { cash: 45 },
        effect: { faction: { mantid: 6 }, cash: 90, disclosure: 2 },
        note: "The Directorate pays for the cores and does not share the analysis.",
      },
    ],
  },
];
