// Vocabulario de ranuras para la edición Gran Colombia.
//
// Nota de gramática, que es la razón por la que esto no es una traducción del
// inglés: la plantilla rellena la ranura con un texto que ya trae su artículo,
// así que el género se resuelve dentro de cada entrada. Lo que NO se resuelve
// solo es el número — «dos seminaristas informa» está mal —, de modo que las
// plantillas de este mazo se escriben con construcciones que no exigen
// concordancia con el verbo: «Según {witness}, …», «Declaración de {witness}».

export const VOCAB: Record<string, readonly string[]> = {
  witness: [
    "un sargento de la policía departamental",
    "dos seminaristas de vacaciones",
    "un fumigador de cultivos",
    "el turno de noche de un trapiche",
    "un conductor de expreso y once pasajeros",
    "una maestra rural viuda",
    "una patrulla de boy scouts y su jefe",
    "tres guardias nacionales fuera de servicio",
    "el proyeccionista de un cine de pueblo",
    "la congregación entera de una vigilia evangélica",
    "un vigía de incendios forestales",
    "un cartero de vereda",
    "un perito de seguros de la capital",
    "una familia de seis que volvía de un velorio",
    "un vaquero del hato y su hijo",
    "el radioperador de una pista de fumigación",
  ],
  official: [
    "la Fuerza Aérea",
    "la Defensa Civil",
    "el gobernador del departamento",
    "la alcaldía",
    "el obispo de la diócesis",
    "el Instituto Geofísico",
    "la Guardia Nacional",
    "un vocero de la gobernación",
    "el comando de la brigada",
    "la capitanía de puerto",
  ],
  oddity: [
    "los perros del caserío no ladraron en toda la noche",
    "las reses amanecieron amontonadas contra la cerca del fondo",
    "la radio sólo daba estática en esa frecuencia",
    "el reloj del campanario se atrasó nueve minutos",
    "quedó un anillo de pasto quemado y perfectamente circular",
    "el agua del aljibe sabía a metal durante tres días",
    "las brújulas de los pescadores señalaban al cerro",
    "no se oyó un solo insecto hasta el amanecer",
    "la leche se cortó en todo el corregimiento",
    "los pájaros se fueron y tardaron dos semanas en volver",
    "el motor de la chiva se apagó y volvió a arrancar solo",
    "la fotografía salió velada, y sólo esa",
    "el ganado no quiso beber de esa quebrada en un mes",
    "hubo olor a azufre hasta bien entrada la mañana",
  ],
  paper: [
    "EL TIEMPO",
    "EL ESPECTADOR",
    "EL NACIONAL",
    "EL UNIVERSO",
    "LA PRENSA",
    "EL COMERCIO",
    "PANORAMA",
    "EL HERALDO",
    "ÚLTIMAS NOTICIAS",
    "LA PATRIA",
  ],
  creature: [
    "una figura pequeña y peluda",
    "algo alto que no proyectaba sombra",
    "tres siluetas delgadas junto al camino",
    "un hombre pálido que no parpadeaba",
    "una forma encorvada que se movía a saltos",
    "algo con demasiados codos",
  ],
  object: [
    "un disco luminoso",
    "una esfera del tamaño de una casa",
    "tres luces en formación de triángulo",
    "un cigarro plateado sin ventanas",
    "una luz que se dividió en dos y volvió a juntarse",
    "algo que se quedó quieto donde no se puede quedar quieto nada",
  ],
  town: [
    "el corregimiento",
    "la vereda",
    "el caserío",
    "el municipio",
    "el pueblo",
  ],
  hoaxer: [
    "un fotógrafo de bodas con demasiado tiempo libre",
    "el hijo del alcalde y una linterna",
    "un vendedor de enciclopedias",
    "dos estudiantes de bachillerato con un plato de aluminio",
  ],
  believer: [
    "un club de radioaficionados",
    "una revista de misterio de la capital",
    "un cura que lleva veinte años tomando notas",
    "un profesor de física que ya no encuentra explicación",
    "un grupo de contactados que se reúne los sábados",
  ],
};
