#!/usr/bin/env node
/**
 * Bundles the whole game into ONE self-contained HTML file.
 *
 * The target is a host that blocks every external request (Claude Artifacts):
 * no CDN, no /_next chunk loading, no /plates/*.png. So everything — React, the
 * engine, the compiled Tailwind, all 63 halftone plates — has to be inlined.
 *
 * Two pipelines feed it:
 *   CSS  next build, then lift the compiled stylesheet out of .next/static.
 *        Reusing the real build means the artifact can't drift from dev.
 *   JS   esbuild, with @/game/photos swapped for a wrapper whose plateFor()
 *        returns data: URIs instead of /plates paths.
 *
 * Usage: node scripts/genartifact.mjs [outfile] [--skip-build]
 */

import { execSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "src");
const OUT = resolve(process.argv[2] && !process.argv[2].startsWith("--") ? process.argv[2] : join(ROOT, "dist/ufologistics.html"));
const SKIP_BUILD = process.argv.includes("--skip-build");

const kb = (n) => `${(n / 1024).toFixed(0)}KB`;

/** Every file under `dir` with the given extension. */
function walk(dir, ext, acc = []) {
  if (!existsSync(dir)) return acc;
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, ext, acc);
    else if (extname(p) === ext) acc.push(p);
  }
  return acc;
}

// --- 1. CSS ----------------------------------------------------------------
if (!SKIP_BUILD) {
  console.log("· next build (for the compiled stylesheet)…");
  execSync("npx next build", { cwd: ROOT, stdio: "inherit" });
}

const cssFiles = walk(join(ROOT, ".next/static"), ".css");
if (cssFiles.length === 0) {
  throw new Error("No compiled CSS under .next/static — run without --skip-build.");
}
// More than one stylesheet would make concatenation order significant, and
// nothing here should produce a split. Fail loudly rather than guess.
if (cssFiles.length > 1) {
  throw new Error(`Expected 1 stylesheet, found ${cssFiles.length}:\n${cssFiles.join("\n")}`);
}
/**
 * Unwrap `@layer name { ... }` blocks and drop the `@layer a, b, c;` ordering
 * statement.
 *
 * The artifact host injects its own unlayered CSS reset, and an unlayered rule
 * beats ANY layered rule regardless of specificity. Tailwind v4 emits all of
 * its utilities inside `@layer utilities`, so a host reset of `* { padding: 0 }`
 * silently zeroes every padding and margin utility in the game — the HUD ends up
 * flush against the screen edge. Flattening keeps source order (base still
 * precedes utilities)
 * while restoring normal specificity, which the reset then loses to.
 */
function flattenLayers(input) {
  let css = input.replace(/@layer[^{;]*;/g, "");
  for (let pass = 0; pass < 5; pass++) {
    const re = /@layer\s+[A-Za-z0-9_-]+\s*\{/g;
    let out = "", last = 0, m, found = false;
    while ((m = re.exec(css))) {
      found = true;
      out += css.slice(last, m.index);
      let depth = 1, j = m.index + m[0].length;
      for (; j < css.length && depth > 0; j++) {
        if (css[j] === "{") depth++;
        else if (css[j] === "}") depth--;
      }
      out += css.slice(m.index + m[0].length, j - 1);
      last = j;
      re.lastIndex = j;
    }
    if (!found) break;
    css = out + css.slice(last);
  }
  return css;
}

const css = flattenLayers(readFileSync(cssFiles[0], "utf8"));
if (/@layer/.test(css)) throw new Error("@layer survived flattening — host reset would win.");
console.log(`· css ${kb(css.length)} (layers flattened)`);

// --- 2. Plates as data URIs ------------------------------------------------
const plateDir = join(ROOT, "public/plates");
const plates = {};
for (const name of readdirSync(plateDir)) {
  if (extname(name) !== ".png") continue;
  const b64 = readFileSync(join(plateDir, name)).toString("base64");
  plates[name.slice(0, -4)] = `data:image/png;base64,${b64}`;
}
const plateBytes = Object.values(plates).reduce((n, s) => n + s.length, 0);
console.log(`· plates ${Object.keys(plates).length} files, ${kb(plateBytes)} inlined`);

const tmp = mkdtempSync(join(tmpdir(), "bt-artifact-"));
const photosShim = join(tmp, "photos-inline.ts");
writeFileSync(
  photosShim,
  `// Generated by scripts/genartifact.mjs — do not edit.
export type { Plate } from ${JSON.stringify(join(SRC, "game/photos"))};
export { PHOTOS } from ${JSON.stringify(join(SRC, "game/photos"))};
const DATA: Record<string, string> = ${JSON.stringify(plates)};
export function plateFor(siteId: string): string | null {
  return DATA[siteId] ?? null;
}
`,
);

// --- 3. JS -----------------------------------------------------------------
const entry = join(tmp, "entry.tsx");
writeFileSync(
  entry,
  `import { createRoot } from "react-dom/client";
import GameShell from "@/components/game/GameShell";

createRoot(document.getElementById("bt-root")!).render(<GameShell />);
`,
);

const inlinePhotos = {
  name: "inline-photos",
  setup(build) {
    build.onResolve({ filter: /^@\/game\/photos$/ }, () => ({ path: photosShim }));
  },
};

const bundle = await esbuild.build({
  entryPoints: [entry],
  bundle: true,
  minify: true,
  format: "iife",
  target: ["es2020"],
  jsx: "automatic",
  platform: "browser",
  absWorkingDir: ROOT,
  tsconfig: join(ROOT, "tsconfig.json"),
  // The entry lives in the OS temp dir, so walking up from it never reaches
  // the project's node_modules. Point resolution at it explicitly.
  nodePaths: [join(ROOT, "node_modules")],
  define: { "process.env.NODE_ENV": '"production"' },
  plugins: [inlinePhotos],
  write: false,
  logLevel: "warning",
});
const js = bundle.outputFiles[0].text;
console.log(`· js ${kb(js.length)}`);

// --- 4. Assemble -----------------------------------------------------------
// The edition boot script is the single source of truth in layout.tsx; lifting
// it verbatim keeps the artifact from flashing the wrong theme differently to
// the app.
const layout = readFileSync(join(SRC, "app/layout.tsx"), "utf8");
const themeBoot = layout.match(/const THEME_BOOT = `([\s\S]*?)`;/)?.[1];
if (!themeBoot) throw new Error("Could not lift THEME_BOOT out of layout.tsx");

// The host owns <head>, so the viewport tag has to be injected. Mirrors the
// `viewport` export in layout.tsx: the map does its own pinch-zoom and must
// not fight the browser's.
const BOOT = `${themeBoot}
document.body.classList.add("min-h-svh","antialiased");
var m=document.createElement("meta");m.name="viewport";
m.content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no";
document.head.appendChild(m);`;

const html = `<title>Ufologistics</title>
<style>${css}</style>
<script>${BOOT}</script>
<div id="bt-root"></div>
<script>${js}</script>
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, html);
console.log(`\n✓ ${OUT}  ${kb(html.length)} total`);
